### ISSUE TITLE
Provide more metadata for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [bk138/multivnc#100]
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by bk138** [comment]
Help with this is greatly appreciated!

**Comment by mondlicht-und-sterne** [comment]
maybe this link will help you?

https://gitlab.com/snippets/1895688

**Comment by bk138** [comment]
> maybe this link will help you?
> 
> https://gitlab.com/snippets/1895688

A pull request containing the already filled-out structure would help me even more ;-)

**Comment by mondlicht-und-sterne** [comment]
You don't have to provide screenshots, but it would look nicer.

**Comment by gujjwal00** [comment]
@bk138 Let me see what I can do about this.

@mondlicht-und-sterne Repeating the same thing and opening duplicate issues will not magically fix this.
