### ISSUE TITLE
Add encoding selector

### ISSUE THREAD

**Issue by nagasawa** [bk138/multivnc#102]
I want you to support raw image quality because it is used in the local environment with termux etc.

**Comment by bk138** [comment]
We already support raw encoding. The desktop version has an encoding selector, for the android one you have to configure the server. Which multivnc version are you using?

**Comment by maruime** [comment]
I using version 1.9.7.

**Comment by nagasawa** [comment]
In the case of localhost, we have made provisional support for live forwarding.
In the case of local, compression will put a load and the image quality will deteriorate, so there is no merit at all.

**Comment by nagasawa** [comment]
I summarized how to prepare a web development environment with android.
https://github.com/nagasawa/multivnc/wiki/Web-development-in-Android

**Comment by bk138** [comment]
@nagasawa https://github.com/nagasawa/multivnc/commit/08479f65cb84d1674237c3358f71d8761b12293d looks like a valid stop-gap improvement until a full selector dialog is implemtend. Would you like to file a PR?

**Comment by nagasawa-umebius** [comment]
Yes, this is a temporary response. Implementing the full selector dialog is costly, so we did it in an easy way. If the implementation of the full selector dialog is postponed, it would be helpful if you could include it.

**Comment by bk138** [comment]
> Yes, this is a temporary response. Implementing the full selector dialog is costly, so we did it in an easy way. If the implementation of the full selector dialog is postponed, it would be helpful if you could include it.

Yes, please go ahead and file a pull request!
