### ISSUE TITLE
Build failed,

### ISSUE THREAD

**Issue by ghcui** [bk138/multivnc#105]
Compile according to the steps you provided, but the compilation is not successful.
as follows:
E:\gitee\multivnc\android\app\src\main\cpp\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error at E:/gitee/multivnc/libressl/crypto/CMakeLists.txt:943 (file):
  file failed to open for reading (No such file or directory):

    E:/gitee/multivnc/libressl/crypto/crypto.sym

**Comment by bk138** [comment]
Would you be able to help if you received one line of log? ;-)

**Comment by ghcui** [comment]
Perform the step，“./prepareLibreSSL.sh”，
return 
pulling upstream openbsd source
HEAD is now at c10a2a56a bump for LibreSSL 3.0.1
libcrypto version 45:5:0
libssl version 47:6:0
libtls version 19:7:0
Added OID dsa
objects.txt:41:Undefined identifier X9_62_id_fieldType


I don't know if it will affect build result.

thanks!

**Comment by bk138** [comment]
You might want to ask over at https://github.com/libressl-portable if they actually support building on Windows.

**Comment by ghcui** [comment]
Maybe I didn’t ask clearly, in fact I’m building AndroidMultiVNC to report an error.

**Comment by ghcui** [comment]
![image](https://user-images.githubusercontent.com/13377017/103047468-96c0f000-45c6-11eb-85c7-83c68ddfc81e.png)

**Comment by bk138** [comment]
As you can see, the error is in the libressl git submodule, hence you should ask over at https://github.com/libressl-portable

**Comment by bk138** [comment]
Closing for now as this seems to be a LibreSSL issue.
