### ISSUE TITLE
Cannot navigate to bookmark on non-touch devices

### ISSUE THREAD

**Issue by 12425** [bk138/multivnc#114]
Firstly, thank you for the Android app. It's the fastest vnc viewer I've ever tried.

I'm using the app on my Android TV. It works well, except that I have to use a mouse to open the bookmark.
There are only arrow keys on TV remote controller. In the landing page, I can't navigate to the bookmarks at the left side.
I'm OK to use a keyboard every first time I connect a device. After bookmarked, I hope I could open it only with arrow keys.

Thank you again!

**Comment by bk138** [comment]
Thanks for reporting! How would one be able to reproduce this with a smartphone and bluetooth keyboard? That's the gear I have that comes closest...

**Comment by bk138** [comment]
Other idea: have you tried circling around with `Tab`?

**Comment by 12425** [comment]
Other than bluetooth keyboard, how about Android emulator, or something like `scrcpy`?
I believe `Tab` will work, but my TV remote only has arrow keys.
Or how about just make the 1st bookmark as the default focused cursor? I don't know Android UI, but in HTML, `autofocus` does the thing.

**Comment by bk138** [comment]
@12425 works for me now with the cursor keys of a bluetooth keyboard. I get stuck on the 'Address' EditText though were only `Tab` takes focus to the next one, not `Down`. How about your remote?

**Comment by bk138** [comment]
If we need to "fix" the EditText fields, https://stackoverflow.com/a/24180423/361413 will help.

**Comment by 12425** [comment]
Thanks!
I can navigate among address, port, etc. so I think it will work.
I'm looking forward to the new version in F-Droid! Thank you!
