### ISSUE TITLE
Android: Switch to Room for database handling

### ISSUE THREAD

**Issue by gujjwal00** [bk138/multivnc#116]
So I took a look at it and so far only [Importing from XML](https://github.com/bk138/multivnc/blob/master/android/app/src/main/java/com/coboltforge/dontmind/multivnc/ImportExportActivity.java#L59-L62) seems to be affected.

It requires access  to `SQLiteOpenHelper` but Room only gives us access to `SupportSQLiteOpenHelper`. We don't have source code for the importer so we can't refactor it either.

Barring this, we *should* be able to switch easily.

**Comment by bk138** [comment]
I actually see no big benefit in exporting/importing the DB in XML format, are there any arguments against a binary dump? If we go for binary dumps, it would still be nice to at least be able to import the old (XML) format for the sake of backwards compat...

**Comment by gujjwal00** [comment]
> So I took a look at it and so far only Importing from XML seems to be affected.

Scratch that. We can implement a custom `SQLiteOpenHelper` just for `ImportExportActivity`.

> I actually see no big benefit in exporting/importing the DB in XML format, are there any arguments against a binary dump?

Exporting/importing through XML is a much safer choice:
1. It only changes the data and not schema. So if we add/modify a column in next version, importing an old binary dump will overwrite our changes.
2. We don't bypass the database library. So we don't have to worry about db cache/journal.

**Comment by bk138** [comment]
> > So I took a look at it and so far only Importing from XML seems to be affected.
> 
> Scratch that. We can implement a custom `SQLiteOpenHelper` just for `ImportExportActivity`.

OK, let's go this way.

> 
> > I actually see no big benefit in exporting/importing the DB in XML format, are there any arguments against a binary dump?
> 
> Exporting/importing through XML is a much safer choice:
> 
>     1. It only changes the data and not schema. For example if we add/modify a column in next version, importing an old binary dump will overwrite our changes.

Right, I haven't thought of that.

> 
>     2. We don't bypass the database library. So we don't have to worry about db cache/journal.

I think there's surely some kinda "flush" operation but 1. rules binary dump out already.
