### ISSUE TITLE
building bailed

### ISSUE THREAD

**Issue by poilynx** [bk138/multivnc#12]
Hi.
I try to build the project. the output is following text.

```sh
$ make
................
VNCConn.cpp:961:7: error: use of undeclared identifier 'Create'
  if( Create() != wxTHREAD_NO_ERROR )
      ^
VNCConn.cpp:1046:7: error: use of undeclared identifier 'Create'
  if( Create() != wxTHREAD_NO_ERROR )
      ^
2 warnings and 2 errors generated.
make[3]: *** [VNCConn.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

> error: use of undeclared identifier 'Create'

I can not find Create symbol implement in VNCConn.h or VNCConn.c, how can I compile it correctly?

thank you.

**Comment by bk138** [comment]
hi!
please attach your complete build logs!
thanks! 

Am 15. November 2018 09:16:55 MEZ schrieb poilynx <notifications@github.com>:
>Hi.
>I try to build the project. the output is following text.
>
>```sh
>$ make
>................
>VNCConn.cpp:961:7: error: use of undeclared identifier 'Create'
>  if( Create() != wxTHREAD_NO_ERROR )
>      ^
>VNCConn.cpp:1046:7: error: use of undeclared identifier 'Create'
>  if( Create() != wxTHREAD_NO_ERROR )
>      ^
>2 warnings and 2 errors generated.
>make[3]: *** [VNCConn.o] Error 1
>make[2]: *** [all-recursive] Error 1
>make[1]: *** [all-recursive] Error 1
>make: *** [all] Error 2
>```
>
>> error: use of undeclared identifier 'Create'
>
>I can not find Create symbol implement in VNCConn.h or VNCConn.c, how
>can I compile it correctly?
>
>thank you.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bk138/multivnc/issues/12

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by bk138** [comment]
@poilynx tentatively closing this, please re-open with more info in case the issue persists.
