### ISSUE TITLE
How to enable turbo mode on MultiVNC for Android v1.9.7?

### ISSUE THREAD

**Issue by POTSandSTOP** [bk138/multivnc#120]
When the app first launched, I seem to remember the built-in documentation provided the steps for turbo mode but I can't figure out how to show the documentation again. What am I missing?

I've installed MultiVNC as an Android app on my Chromebook. I'm in the beta tester program.

**Comment by bk138** [comment]
Sorry to ask, but what do you refer to as "turbo mode"?

**Comment by bk138** [comment]
Closing for now, feel free to re-open if there's more info.
