### ISSUE TITLE
gsed: can't read update.sh: No such file or directory ./prepareLibreSSL.sh: line 21: ./autogen.sh: No such file or directory

### ISSUE THREAD

**Issue by mquanying** [bk138/multivnc#130]
gsed: can't read update.sh: No such file or directory
./prepareLibreSSL.sh: line 21: ./autogen.sh: No such file or directory

**Comment by bk138** [comment]
Please!! provide more info. Would you be able to solve an issue with two lines of script output from an unknown environment, without knowing what the user wants to do?

**Comment by bk138** [comment]
Tentatively closing, feel free to come back when there is more info available.
