### ISSUE TITLE
Unmet dependencies in recent Debian/Ubuntu

### ISSUE THREAD

**Issue by alkisg** [bk138/multivnc#134]
Hi, while trying to install multivnc in Ubuntu 20.04 or Debian Bullseye, I'm getting the following errors.

For multivnc-prerelease.deb:

```shell
The following packages have unmet dependencies:
 multivnc : Depends: libwxgtk3.0-0v5 (>= 3.0.4+dfsg) but it is not installable
```

For multivnc_0.5-1_amd64.deb:

```shell
The following packages have unmet dependencies:
 multivnc : Depends: libgcrypt11 (>= 1.4.2) but it is not installable
            Depends: libgnutls26 (>= 2.7.14-0) but it is not installable
            Depends: libwxbase2.8-0 (>= 2.8.10.1) but it is not installable
            Depends: libwxgtk2.8-0 (>= 2.8.10.1) but it is not installable
```

You may browse the available packages at:
https://packages.ubuntu.com/libwxgtk3.0
https://packages.debian.org/libwxgtk3.0

E.g. maybe debian/control should state:
Depends: libwxgtk3.0-gtk3-0v5 | libwxgtk3.0-0v5

Are multiple builds needed, one per supported Debian or Ubuntu version? If so, maybe openSUSE Build Service could be used to provide debs and repositories? See an example from the Palemoon browser:
https://software.opensuse.org/download.html?project=home:stevenpusser&package=palemoon

Of course the best thing would be if multivnc was available in the stock Debian/Ubuntu repositories, I can see a request for package in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762576, I've no idea why this wonderful app isn't already included in Debian! :)

**Comment by bk138** [comment]
I would actually like a flatpak for Linux, would this be of more use than different rpm/deb versions?

**Comment by alkisg** [comment]
Flatpak, appimage and snap packages can be useful for applications that depend on libraries that are not available in the target distribution/version. For example, a new linphone version may depend on Qt 5.6, which isn't available in previous Debian/Ubuntu releases, and it can bundle it inside linphone.appimage.

Distribution repositories have many benefits though. For example, `apt install epoptes` automatically pulls dependencies like x11vnc and vncviewer; the users don't have to read documentation and seek external dependencies and download/install them, before they have a working app.
Running `apt install kdeedu` (the KDE education suite) automatically pulls 249 packages. I really wouldn't want to have to seek all of them one by one!
And, having automatic security updates for applications libraries is a big plus, while the libraries that are bundled in flatpak/appimage/snap packages might get updated much later.

If #135 and #136 get resolved, and with your permission, I'll create a launchpad recipe that will automatically build .deb packages from the git tree for all supported Ubuntu versions; in many cases these are also compatible with Debian, for example: https://code.launchpad.net/~epoptes/+recipe/epoptes-stable
Thank you!

**Comment by alkisg** [comment]
I've set up a launchpad automatic import at:
https://code.launchpad.net/~alkisg/epoptes/+git/main
Anything that you commit here in github will be automatically mirrored there after a few hours.

And, I've set up a launchpad recipe for automatic builds at:
https://code.launchpad.net/~alkisg/+recipe/multivnc-daily

This will run daily, if it detects any code changes, and it will try to build a .deb package for all supported Ubuntu versions.
Unfortunately, there were some build problems:

* The build dependency libwxgtk2.8-dev doesn't exist in Ubuntu >= 16.04, so all the newer Ubuntu builds failed. In Ubuntu 16.04 and 18.04, libwxgtk3.0-dev exists, but not in 20.04. In Ubuntu >= 18.04, libwxgtk3.0-gtk3-dev exists. Would it be possible to change the dependency to `libwxgtk2.8-dev | libwxgtk3.0-dev | libwxgtk3.0-gtk3-dev` ?
* While in Ubuntu 12.04 and 14.04 where libwxgtk2.8-dev exists, the build failed with "[make: *** No rule to make target `configure', needed by `config.status'.  Stop.](https://launchpadlibrarian.net/536583953/buildlog_ubuntu-trusty-i386.multivnc_0.5-1+202104301152~ubuntu14.04.1_BUILDING.txt.gz)". Maybe `cmake` is missing as a build-dep?

If you like the "automatic daily .deb builds" idea, we can keep the mirror and the recipe indefinitely. After any upstream changes, the next day launchpad will retry the builds. If you don't like the idea we can of course delete the mirror and the recipe.

**Comment by bk138** [comment]
Very nice, thanks a lot! I would incorporate a link to https://code.launchpad.net/~alkisg/+recipe/multivnc-daily in the README. Also, please note that https://github.com/bk138/multivnc/blob/master/debian/control is severely outdated as is, the desktop builds actually use CMake and wx3.0.

**Comment by bk138** [comment]
@alkisg what do you think, can this issue be closed now with the recent additions?

**Comment by alkisg** [comment]
@bk138, I think I didn't manage to express my thoughts well enough...

The "multivnc-daily builds service" was depending on your debian/ directory, which needed to be updated.
Now that debian/ was removed, the service won't work at all, no .deb packages will ever be produced.

From what I understand, you don't have enough time currently to maintain a debian/ directory upstream.
In this case, I think we should completely remove the daily builds service, mention that there are no .deb packages for recent Debian/Ubuntu releases, and wait until Debian packages multivnc: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762576

Thank you for your time!

**Comment by bk138** [comment]
Let's see if 441027a65717dcf3cbd0a8745a14bef998970af8 at least solves this here issue :-)

**Comment by alkisg** [comment]
I didn't realize that you were using cpack; I thought the debian/ dir was actually in use!
Yeah if only a single .deb distribution+version can be supported, focal is better than bionic.
