### ISSUE TITLE
Needs protocol version 3.8

### ISSUE THREAD

**Issue by AngelODeath** [bk138/multivnc#139]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android):
android 11

**Which MultiVNC version are you using?**

1.9.11

**Describe the bug**

App crashes when trying to connect to tigervnc on rasbian.

**To Reproduce**

TBA

**Expected Behavior**

Not crash. Maybe give a warning.

**Screenshots**

**For the Desktop Version (please complete the following information):**
 - OS and version:
 - Xorg version used:
 - Wayland version used:

**For the Mobile Version (please complete the following information):**
 - Android version: 11
 - Installed from Play Store, F-Droid, Amazon Appstore: Play Store

**Additional context**

**Comment by bk138** [comment]
Tentatively closing, please post again here/re-open if issue persists.
