### ISSUE TITLE
Too much wasted space for key combo toolbar on Android

### ISSUE THREAD

**Issue by afcady** [bk138/multivnc#14]
As a general principle, UI bars waste the least useful space when placed across the smaller dimension of the screen.  This toolbar is taking away a lot of the screen.  It should be possible to hide, and to put onto the smaller dimension (which should be the default).

**Comment by JakobBerg** [comment]
or maybe just enable a full screen mode?

**Comment by bk138** [comment]
aa3ae3d6d7fa9dcdfa780b5ca867e26aacdb4aa8 is a start in an ongoing effort to update the app's UI to Material design. Support via https://liberapay.com/bk138/donate always welcome :-)
