### ISSUE TITLE
Add a Dark theme

### ISSUE THREAD

**Issue by Mhowser** [bk138/multivnc#142]
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your feature request about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android): mobile 
 - If Mobile, installed from Play Store or F-Droid: fdroid

**Is your feature request related to a problem? Please describe.**

The regular theme hurts my eyes and doesn't match my system theme
**Describe the solution you'd like**

Add a dark theme with optional automatic system wide detection
**Describe alternatives you've considered**

None
**Additional context**

N/A

**Comment by bk138** [comment]
Thanks fr the idea! It would be nice to have a dark theme so the app UI could adopt to system dark mode. Contributions very welcome!

**Comment by gujjwal00** [comment]
I can work on it (should be easy, given our UI is relatively simple)

**Comment by bk138** [comment]
> I can work on it (should be easy, given our UI is relatively simple)

Cool, go ahead 👍.
