### ISSUE TITLE
Can't rotate Android app

### ISSUE THREAD

**Issue by afcady** [bk138/multivnc#15]
The orientation is fixed horizontal.   It should either rotate when the device is rotated, or else be a setting per connection.

**Comment by bk138** [comment]
https://developer.android.com/guide/topics/resources/runtime-changes

**Comment by bk138** [comment]
# Status Quo
There is https://github.com/bk138/multivnc/tree/android-rotatable-canvasactivity that contains one commit regarding this issue

# Challenges

- [ ] Decide whether to do activity restart or keep activity and handle configuration changes

- [ ] In either case, pointer highlight position is set off after rotation. Needs a fix.

- [ ] Zoom states are messed up after rotation.

- [ ] Sometimes parts of the screen are missing after rotation, probably only needs a framebuffer request.

**Comment by gujjwal00** [comment]
> Decide whether to do activity restart or keep activity and handle configuration changes   

Activity restarts ( requires decoupling `VNCConn` and `VncCanvas`): 
- Inline with Android framework 👍
- Better design (IMO)  👍
- More effort right now (for refactoring) 👎

Handling configuration change:
- Less refactoring required 👍
- Relatively faster (no restart overhead) 👍
- Higher maintenance  👎

I would argue that we should allow restarts because even if we handle configuration changes, Android can kill the activity if is in background. (*Maybe we can handle changes as an optimization?* ).
 
Related: https://stackoverflow.com/questions/7818717/why-not-use-always-androidconfigchanges-keyboardhiddenorientation

**Comment by gujjwal00** [comment]
>In either case, pointer highlight position is set off after rotation. Needs a fix.

What about showing the pointer highlight only when `TouchPointView` is active (it would still need a fix).

For `VncCanvas` we can try to implement a more intuitive input system.
Touch/Tap -> Left click
Long tap -> Right click
etc...

**Comment by bk138** [comment]
> > Decide whether to do activity restart or keep activity and handle configuration changes
> 
> Activity restarts ( requires decoupling `VNCConn` and `VncCanvas`):
> 
>     * Inline with Android framework +1
> 
>     * Better design (IMO)  +1
> 
>     * More effort right now (for refactoring) -1
> 
> 
> Handling configuration change:
> 
>     * Less refactoring required +1
> 
>     * Relatively faster (no restart overhead) +1
> 
>     * Higher maintenance  -1
> 
> 
> I would argue that we should allow restarts because even if we handle configuration changes, Android can kill the activity if is in background. (_Maybe we can handle changes as an optimization?_ ).
> 
> Related: https://stackoverflow.com/questions/7818717/why-not-use-always-androidconfigchanges-keyboardhiddenorientation

whatever works best for the user - also in terms of performance...

**Comment by bk138** [comment]
> For `VncCanvas` we can try to implement a more intuitive input system.
> Touch/Tap -> Left click
> Long tap -> Right click
> etc...

Only after extensive user testing. I found the current impl works best for multiple users.

**Comment by gujjwal00** [comment]
> whatever works best for the user - also in terms of performance...

I will prepare a proposal.

> Only after extensive user testing. I found the current impl works best for multiple users.

I will try to implement it as optional choice.

**Comment by bk138** [comment]
Closed by #49, thanks, @gujjwal00 !
