### ISSUE TITLE
Esc key problem ...

### ISSUE THREAD

**Issue by Pti-Jean** [bk138/multivnc#154]
MultiVNC V1.9.11
Android 5.1.1

Hello,

Message translated with Google Translate ... Original version in French below ...

Following this message:
https://github.com/bk138/multivnc/issues/138
which for the moment has not had much success ...

I encounter another problem ... The "Esc" key is not taken into account, although it is present on the external keyboard ... I suppose that it is Android which does not manage this key (Esc) ...

Hence question:
Would it not be possible that in the "Send Key Combo", to have the "Esc" key ... (Because the OS towards which I do the remote handling, manages the "Esc" key)

Have a good day,

JM 

#####################################################
Bonjour,

Message traduit avec Google Translate... Version originale en français dessous...

Suite à ce message:
https://github.com/bk138/multivnc/issues/138
qui pour le moment n'a pas eu beaucoup de succès...

Je rencontre un autre problème... La touche "Esc" n'est pas prise en compte, bien que présent sur le clavier externe... Je suppose que c'est Android qui ne gère pas cette touche (Esc)...

D'où question:
Serait-il pas possible que dans le "Send Key Combo", d'avoir la touche "Esc"... (Car l'OS vers lequel je fais la prise en main à distance, gère lui la touche "Esc")

Bonne journée,

JM

**Comment by anonimo82** [comment]
I have the same issua, with a different keyboard layout.

**Comment by bk138** [comment]
The "Esc" key is in there, it's called "Escape":

![grafik](https://user-images.githubusercontent.com/80450/209653210-c42e864b-b510-49c3-ae05-cdddbdf5ffb0.png)
