### ISSUE TITLE
Can be treated in MultiVNC a Reseed Screen Size Configuration Event and MTX

### ISSUE THREAD

**Issue by RalfWerner** [bk138/multivnc#169]
Typical for phones/tablets are rotation of the device but also split screen and on devices with [PiP](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-733700709) (popup view) the free choice of the picture`*)` (window) size. In addition, _nonfloating_ OS-KB (On Screen or Soft Keyboard) and EK (Extrakeys) restrict the usable size. [Here](https://user-images.githubusercontent.com/45426380/125047883-b241a300-e09f-11eb-9952-09bd1f22f905.mp4) an example with Termux-X11`**)`. In `~/.vnc/config`, a size is set, which should then be calculated from the above parameters.

Consequently, in this case, a pinch zoom lower 100% was no longer required. Another feature request would then be the option/prereference: **Direct, Mouse** (finger=mouse, I may not have discovered yet) mode. Especially for Direct mode (Generic Events in X11), Pinch or other multitouch actions of VNC are incompatible because this _should be treated_ by the XClient.

`*)` **MultiVNC** supports this function in opposite to **RealVNC**-Viewer (only full screen)
`**)` Is a [XServer](https://github.com/termux/termux-x11) in preparation, based on [Termux](https://github.com/termux/termux-app) Environment and `Xvnc` is the VNC-Server (package) of **Termux**.
<details><summary>Question: Is your app capable of being used as Xserver (open for details) - Examples: next commit and #176 Bug report. </summary>

The topic _Remote maintenance_ I have been dealing with TeamViewer for several years (TV free of charge for my family). As far as I understood, **MultiVNC** is also an alternative to it and I suspect you know the tool and also RealVNC.
In all three tools, limitations are included with X11/Xorg, in which I am insecure, _**whether they can solve at all?**_
The **mouse mode** is at least included in **TV** and PiP-enabled your app is in contrast to **RealVNC**.
### To Termux App and related plugins:
The Termux developers have currently decided to maintain the _targetSdkVersion=**28**_, which excludes the publication on PlayStore. The reason is that the **29** restriction (executeables/ELF files are only allowed in `*.apk`) for a development environment as Linux is _the deadly_. But that does not apply to your App.

For this reason, the app artifacts are offered on F-Droid and Github only. I had inserted above links to **app+X11**, with which you can install/build them yourself. In addition, the plugins **Float+Widget** for multi-session usage are helpful if you like to work with Termux.

I personally like to use the term "One-Touch Start=**OTS**". I can simply explain the process: _tap on_. Currently, I used only in exceptional cases the package `Xvnc` (otherwise `Xwayland`=PID3) to start the four processes of [OTS](https://github.com/termux/termux-float/issues/37#issuecomment-916777123) with XClient=PID4. PID1 is Termux and here is PID2=MultiVNC started with:`am start -n com.coboltforge.dontmind.multivnc/.MainMenuActivity`
</details>

**MT**=MultiTouch should be treated at least optionally by the XClients (**MTX**), which excludes processing by **MultiVNC** and **EK**= ExtraKeys should be outside the ReseedScreen (below). The green circle is therefore to be converted in **EK** and it is also a switch (as with **TV**: blue circle/arrow in **EK** at Phone/Pad) necessary, that activates **MTX. MultiVNC** uses **MT** at Zoom/Pinch and for the (emulated) Mouse Buttons (MB*). The MB* itself are also **MT** and with each Key/Button increases the number of possible actions expaceentially `***)`.

**RS**=Reseed Screen means everything is visible also _without_ screen-shift and _mouse mode_ (pointer=finger as in **TV,X11**) works and nothing is covered by non-Xclient-Ornaments (except floating KB), 

`***)` Is `+/-` Press/Release, in between possibly a move and `*=1` (mostly left) there is only one: `+1-1` action -e.g. _S-Pen_.
At `*=2`, there are six: `+1-1, +2-2, +1+2-2-1, +1+2-1-2, +2+1-1-2, +2+1-2-1` Actions such as: `+1+2-1+1-2-1` are not counted and I consider an action as finished when all MB has been released.

Mice are mostly `*=3`, only two point geometries between `+/-` and switch on most devices/emulations into another mode with simultaneous `+` multiple MB. There may also be several mice/touchpads connected and weel rotation corresponds usually to `+,-` with `*=4/5` for forward/backwards

Finger actions are comparable but `*` is not limited and each finger has its own `+/-` point geometries (Direct mode only).
Furthermore, an action for different Windows can be implemented differently and the `+` fingers of an action are made on different Windows.

To check **MultiVNC** and the alternative comparison apps, phones/tablets whose **scrcpy/TV** reflection can be used to a PC or AVD emulation. Unfortunately, all these alternatives behave different or do not allow some actions. The _desired_ **MT/RS** behavior can be seen with the **X11** app on _real_ Phones/Tablets.

**Comment by bk138** [comment]
I still have trouble understanding the exact feature request. https://ddbeck.com/bug-reports-that-get-results/ has some info on how to achieve a good feature request. Please make this easy for me to digest: a short and concise text, say 500 chars max.

**Comment by RalfWerner** [comment]
> Please make this easy for me to digest: a short and concise text, say 500 chars max.

The two sections [above](https://github.com/bk138/multivnc/issues/169#issue-1028793377) behind **> Question:** are 546 characters and describe it well.
As I wrote to you, I was _surprised by **Multi-Touch**_ and you said: "Yes, that's a feature and should do so :)" - so there is still hope. But if the effort is too high, you can also close this issue.

**Comment by bk138** [comment]
Hmm, I maybe got it ;-): 

* MultiTouch: this cannot easily be conveyed by the RFB protocol, so: No. (There's multitouch highlight
 in the "Touchpad" mode, but that's a client-side visual indication only.
* "Reseed Screen": Nope, won't work on exaclty this, but you might find bits and pieces of this in https://github.com/bk138/multivnc/projects/2

**Comment by RalfWerner** [comment]
> MultiTouch: this cannot **easily** be conveyed by the RFB protocol, so: **No.**

Now, I did not understand that! The VNC Client - So here **MultiVNC** is the only tool with which I edit the XClient! In my case, touch.c (in **ip.zip**) is MT-enabled and I can decide that with the touch/move of the two windows with two fingers, they are moved on the screen - or something else, instead of a pinch-zoom always. Still **No.** or simply **not easy**?
> "RS" Nope, won't work on exaclty this

Reseed Screen works for **RealVNC** and **TeamViewer** and also **X11** exactly so! If the result of the **Polish Project** is, that the ornaments of the Window-Manager are visible at any time and can be used at any time, that's also Ok.

**Comment by RalfWerner** [comment]
### Notes on the _"Polish project"_ and some of the requests R:
Apparently many of the requester are familiar with Termux - you too in between?
R: #156 is identical with my to **EK**=ExtraKeys Request. At best with the Termux-edited variant and please outside the RS, which is partially faulty in **X11**. This variant has the advantage that most problems with the **EK** lines are already solved.
R: #124 Would then be superfluous if **fullscreen** (always in **MultiVNC**) is working at the same time
R; #162 Behind the 546 char (above) I have described the **MB**=mouse button options that are possible but currently do not all work correct (not just MB3). It would be easier to integrate MB in EK and escapably to Shift/ALT with a single/permanent function. Thus, then **RS** is possible. R: #58 And a few others would then be superfluous.
R: #161 Handles the comparison with **bVNC** and different modes. I'll test the tool too. To touch screen/pad mode, I had something described above and the praise for the S-Pen support I closed myself without restriction.
