### ISSUE TITLE
Native libvncclient support with 2.x.x will realise support for OSX, newer vino versions and TurboVNC

### ISSUE THREAD

**Issue by sultanahamer** [bk138/multivnc#17]
What would be tentative timeline?

**Comment by bk138** [comment]
Hi! I reckon this is about the Android client? For this there's a lot of work, let's use this issue to keep track of progress?

**Comment by bk138** [comment]
https://stackoverflow.com/questions/8578002/android-tutorials-for-opengl-es-2-0-using-the-ndk

**Comment by bk138** [comment]
vino auth also does not work, see #25

**Comment by bk138** [comment]
https://stackoverflow.com/questions/9087563/maximum-native-memory-that-can-be-allocated-to-an-android-app

**Comment by bk138** [comment]
https://github.com/viaduck/openssl-cmake

**Comment by bk138** [comment]
https://github.com/openssl/openssl/issues/7878

**Comment by bk138** [comment]
https://developer.android.com/ndk/guides/other_build_systems

**Comment by bk138** [comment]
https://stackoverflow.com/questions/45837496/compiling-libgcrypt-and-libgpgerror-for-android-with-cmake

**Comment by bk138** [comment]
working on host: `cmake .. -DOPENSSL_INCLUDE_DIR=/home/bk/Projekte/PROGGA/multivnc/libressl/include -DOPENSSL_SSL_LIBRARY=/home/bk/Projekte/PROGGA/multivnc/libressl/build/ssl/libssl.a -DOPENSSL_CRYPTO_LIBRARY=/home/bk/Projekte/PROGGA/multivnc/libressl/build/crypto/libcrypto.a`

**Comment by sultanahamer** [comment]
> # general notes
> 
>     * https://stackoverflow.com/questions/9087563/maximum-native-memory-that-can-be-allocated-to-an-android-app -> no memory restriction for native part
> 
>     * https://developer.android.com/training/articles/perf-jni -> general JNI perf tips
> 
> 
> # TODOs
> 
>     * [x]  document drawing models -> we'll use the existing GLSurfaceView with native draing calls
> 
>     * [x]  create a selection dialog
> 
>     * [ ]  connect framebuffer drawing
> 
>     * [ ]  connect mouse input
> 
>     * [x]  connect keyboad input
> 
>     * [ ]  version && style beta
> 
>     * [ ]  upload beta
> 
>     * [ ]  create a notification dialog to try out beta
> 
>     * [ ]  add encryption
> 
> 
> # how to interface libVNCClient:
> ## fat native VNCConn with threading and all in native part
> 
>     * re-use wx VNCConn.cpp?
>       
>       * lotsa wx deps in there, maybe easier with slim approach
> 
> 
> ## slim native VNCConn with threading in Java part
> 
>     * provide JNI wrappers for some or all rfbClient.h functions
> 
>     * what about C callbacks -> need to be in native as well
> 
>     * [8198a0a](https://github.com/bk138/multivnc/commit/8198a0a0a6f636b6dc4067fde83a3fcd23b54a69) might be re-usable
> 
> 
> # how to draw framebuffer
> ## hook GLSurfaceView to native drawing code
> 
>     * framebuffer resides in native part, no Java heap restrictions 👍
> 
>     * https://www.learnopengles.com/calling-opengl-from-android-using-the-ndk/
> 
> 
> ## use a NativeActivity and draw natively
> 
>     * framebuffer resides in native part, no Java heap restrictions 👍
> 
>     * what about the existing UI controls then? -> https://stackoverflow.com/questions/12822185/is-it-possible-to-create-ui-elements-with-the-ndk-lack-of-specs-in-android-d -> seems possible 😐
> 
>     * https://github.com/android/ndk-samples/blob/master/teapots/classic-teapot/src/main/java/com/sample/teapot/TeapotNativeActivity.java native and java code
> 
>     * ❗️ check if java onclicklisteners work there as well -> yes 👍
> 
> 
> ## use direct ByteBuffer
> 
>     * framebuffer resides in Java part, Java heap restrictions 👎
> 
>     * https://developer.android.com/training/articles/perf-jni#faq:-how-do-i-share-raw-data-with-native-code
> 
>     * https://stackoverflow.com/questions/4841340/what-is-the-use-of-bytebuffer-in-java
> 
>     * https://stackoverflow.com/questions/28791827/does-newdirectbytebuffer-create-a-copy-in-native-code
> 
> 
> ## use Android jnigrpahics native API
> 
>     * framebuffer resides in Java part, Java heap restrictions 👎
> 
>     * https://developer.android.com/ndk/reference/group/bitmap
> 
>     * https://android.googlesource.com/platform/frameworks/base/+/jb-release/native/graphics/jni/bitmap.cpp
> 
>     * https://stackoverflow.com/questions/5605853/what-is-jni-graphics-or-how-to-use-it
> 
> 
> ## implement a LibVNCClient buffer alloc that uses JNI allocation or implement a LibVNCClient method that takes a framebuffer declared in Java
> 
>     * framebuffer resides in Java part, Java heap restrictions 👎
> 
>     * i.e. `NewByteArray()`
> 
> 
> ```
> //fill the buffer
>     jbyteArray jBuff = _env->NewByteArray(b->Length);       
>     _env->SetByteArrayRegion(jBuff, 0, b->Length, (jbyte*) buff);
> ```
> 
>     * https://stackoverflow.com/questions/8574241/jni-newbytearray-memory-leak
> 
>     * https://stackoverflow.com/questions/1610045/how-to-return-an-array-from-jni-to-java
> 
>     * mh maybe, but rather go for extending LibVNCClient so it takes a pre-allocated pointer
> 
>     * might be copying arrays: https://developer.android.com/training/articles/perf-jni#faq:-how-do-i-share-raw-data-with-native-code 👎
> 
> 
> ## hand the malloc'ed buffer over to Java -> possible _without_ copying?
> 
>     * apparently not -> https://stackoverflow.com/questions/25368049/custom-memory-allocation-inside-jni-native-function 👎

Is the today list updated with whats done and whats pending? Wanted to check because it was last edited on Sep15 and there are very recent commits referring this issue.

**Comment by bk138** [comment]
> > # general notes
> > ```
> > * https://stackoverflow.com/questions/9087563/maximum-native-memory-that-can-be-allocated-to-an-android-app -> no memory restriction for native part
> > 
> > * https://developer.android.com/training/articles/perf-jni -> general JNI perf tips
> > ```
> > 
> > 
> > # TODOs
> > ```
> > * [x]  document drawing models -> we'll use the existing GLSurfaceView with native draing calls
> > 
> > * [x]  create a selection dialog
> > 
> > * [ ]  connect framebuffer drawing
> > 
> > * [ ]  connect mouse input
> > 
> > * [x]  connect keyboad input
> > 
> > * [ ]  version && style beta
> > 
> > * [ ]  upload beta
> > 
> > * [ ]  create a notification dialog to try out beta
> > 
> > * [ ]  add encryption
> > ```
> > 
> > 
> > # how to interface libVNCClient:
> > ## fat native VNCConn with threading and all in native part
> > ```
> > * re-use wx VNCConn.cpp?
> >   
> >   * lotsa wx deps in there, maybe easier with slim approach
> > ```
> > 
> > 
> > ## slim native VNCConn with threading in Java part
> > ```
> > * provide JNI wrappers for some or all rfbClient.h functions
> > 
> > * what about C callbacks -> need to be in native as well
> > 
> > * [8198a0a](https://github.com/bk138/multivnc/commit/8198a0a0a6f636b6dc4067fde83a3fcd23b54a69) might be re-usable
> > ```
> > 
> > 
> > # how to draw framebuffer
> > ## hook GLSurfaceView to native drawing code
> > ```
> > * framebuffer resides in native part, no Java heap restrictions 👍
> > 
> > * https://www.learnopengles.com/calling-opengl-from-android-using-the-ndk/
> > ```
> > 
> > 
> > ## use a NativeActivity and draw natively
> > ```
> > * framebuffer resides in native part, no Java heap restrictions 👍
> > 
> > * what about the existing UI controls then? -> https://stackoverflow.com/questions/12822185/is-it-possible-to-create-ui-elements-with-the-ndk-lack-of-specs-in-android-d -> seems possible 😐
> > 
> > * https://github.com/android/ndk-samples/blob/master/teapots/classic-teapot/src/main/java/com/sample/teapot/TeapotNativeActivity.java native and java code
> > 
> > * ❗️ check if java onclicklisteners work there as well -> yes 👍
> > ```
> > 
> > 
> > ## use direct ByteBuffer
> > ```
> > * framebuffer resides in Java part, Java heap restrictions 👎
> > 
> > * https://developer.android.com/training/articles/perf-jni#faq:-how-do-i-share-raw-data-with-native-code
> > 
> > * https://stackoverflow.com/questions/4841340/what-is-the-use-of-bytebuffer-in-java
> > 
> > * https://stackoverflow.com/questions/28791827/does-newdirectbytebuffer-create-a-copy-in-native-code
> > ```
> > 
> > 
> > ## use Android jnigrpahics native API
> > ```
> > * framebuffer resides in Java part, Java heap restrictions 👎
> > 
> > * https://developer.android.com/ndk/reference/group/bitmap
> > 
> > * https://android.googlesource.com/platform/frameworks/base/+/jb-release/native/graphics/jni/bitmap.cpp
> > 
> > * https://stackoverflow.com/questions/5605853/what-is-jni-graphics-or-how-to-use-it
> > ```
> > 
> > 
> > ## implement a LibVNCClient buffer alloc that uses JNI allocation or implement a LibVNCClient method that takes a framebuffer declared in Java
> > ```
> > * framebuffer resides in Java part, Java heap restrictions 👎
> > 
> > * i.e. `NewByteArray()`
> > ```
> > 
> > 
> > ```
> > //fill the buffer
> >     jbyteArray jBuff = _env->NewByteArray(b->Length);       
> >     _env->SetByteArrayRegion(jBuff, 0, b->Length, (jbyte*) buff);
> > ```
> > 
> > 
> > ```
> > * https://stackoverflow.com/questions/8574241/jni-newbytearray-memory-leak
> > 
> > * https://stackoverflow.com/questions/1610045/how-to-return-an-array-from-jni-to-java
> > 
> > * mh maybe, but rather go for extending LibVNCClient so it takes a pre-allocated pointer
> > 
> > * might be copying arrays: https://developer.android.com/training/articles/perf-jni#faq:-how-do-i-share-raw-data-with-native-code 👎
> > ```
> > 
> > 
> > ## hand the malloc'ed buffer over to Java -> possible _without_ copying?
> > ```
> > * apparently not -> https://stackoverflow.com/questions/25368049/custom-memory-allocation-inside-jni-native-function 👎
> > ```
> 
> Is the today list updated with whats done and whats pending? Wanted to check because it was last edited on Sep15 and there are very recent commits referring this issue.

yes, it is. but: take the todos as correct, but incomplete, i. e. a quite coarse list.

**Comment by bk138** [comment]
Version 1.8.6 will have support for connection to Mac servers, but no encryption, this will come in 2.x.x.

**Comment by sultanahamer** [comment]
@bk138 will test it once its on fdroid. Do let us know when are you planning to release.
