### ISSUE TITLE
MultiVNC Bugs on architectures arm and x86 (AVD)

### ISSUE THREAD

**Issue by RalfWerner** [bk138/multivnc#176]
Bugs for **MultiVNC** Platform Android Version 2.0.0 for devices with _arch=armebi-v7a_ (Gigaset) and _arch=x86_ (AVD Nexus)

If the following logcat help you to fix the bug (`cache`?) - great! If not, say what you still need. It may not be a _arch_ but a _Gigaset_ problem. With my _Huawei Y7 (arch=aarch64)_ I also have some bugs that sometimes lead to crashes, but report here not, because other apps on _this_ device works faulty too.
![grafik](https://user-images.githubusercontent.com/45426380/144196692-5082a6d0-dee1-428c-9979-7a4a7d12db40.png)
Since nothing to see on AVD,except one of the one in the Shot (Studio) at the app start and only at the Gigaset (German version) Errors in the logcat extract are only  these listed here:
```
# Trennen/Disconnect   "22235-22326/com.coboltforge.dontmind.multivnc" here removed
2021-11-15 09:11:56.069  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
2021-11-15 09:11:56.142  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
2021-11-15 09:12:00.968  E/IMGSRV: :0: PVRSRVFenceDestroyI: Fence close fd=67 failed (Bad file descriptor)
2021-11-15 09:12:00.971  E/IMGSRV: :0: UnlockPostBuffer: Failed to close fence (fd=67,err=PVRSRV_ERROR_INVALID_PARAMS)
# Verbinden/Connect (Gigaset)
2021-11-15 09:12:13.530  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
2021-11-15 09:12:13.559  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
2021-11-15 09:12:13.566  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
2021-11-15 09:12:13.664  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
2021-11-15 09:12:14.243  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
2021-11-15 09:12:14.354  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
# Menue/green circle (no problems with actions of it like KB or MB)
2021-11-15 09:12:25.607  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
2021-11-15 09:12:25.725  E/libc: Access denied finding property "ro.vendor.hwui.texture_cache_size"
```
The **MultiVNC** App is used here with **Termux**`*)` (VNC server). At `x86`, no multi-touch actions are possible and on my _armv7_ device is not a graphic display. With _arch=arm64-v8_, these bugs are not. The steps to reproduce the behavior are somewhat more complex and the bugs can only be explained in comparison with alternative apps (**RealVNC, X11**). I also refer back to #169, where I describe **MultiVNC _potentials_**.

`*)` **Termux** and other apps must be installed on the device (below). For this purpose, [ip.zip](https://www.dropbox.com/s/ug071qoox8gwf1c/ip.zip?dl=0) is used in download, as far as sufficient current apps do not yet exist. Termux contains a basic Linux variant for all four Arch, which is installed by bootstrap during the first opening (arch of the device).

If Linux (`bash, apt, alias` ...) is known, but not **Termux**, here a necessary note:`pkg` is a wrapper to `apt` and supplements the installed packages. To use data outside of **Termux** (e.g., download) this is possible. The X/VNC server/client start is not part of **Termux**, but is explicitly described by `bashrc **)`.

Here four screenshots from the installation environment on an AVD (x86/Nexus) emulator (created with **Studio**). I've used AVD, because `rm *.img.qcow2` simply resets it on the factory setting. The XServer/Xwayland (`DISPLAY=:0` only for comparison) is started together with Termux, as well as Xvnc (`DISPLAY=:1`) the server to the two VNC clients.
![grafik](https://user-images.githubusercontent.com/45426380/142212784-a2d4e481-70b6-4894-a1a7-de4e2ad09025.png)
- 1 Startscreen with the at least required apps (from left/top to the right/bottom) **widget** (contents of the table - later), **Termux+X11** (black below), **RealVNC** (blue) + **MultiVNC** (green), two Google tools (to Download) and **Files+Setup** app. The two ***VNC** can be obtained via PlayStore and the others are part of the OS. To install, however, download should be used (in **Files** with Developer signing). `*.zip` contains next to `apk` (extracted here for download) `uu.sh` and `ip`. After the APK installation (`*02_04` suffices) and allowing everything to start **Termux**. Shots for installation: 
![grafik](https://user-images.githubusercontent.com/45426380/142213017-427e5900-3652-4e79-9ad2-313153d933a4.png)
- 2 Termux `bash` with start message (until `report issues: ...`). The rest until prompt appears only if further actions were made in this `bash` or a new session is opened. The first step is done in the **Files**, which also includes `termux.apk` (do Installing/Open) also contains `uu.sh` that you extract to Termux (folder in **Files**). In Termux, `ls` confirm the copy success and with `. uu.sh .` the script executed (sourced). Thus, data, symlinks and alias have been generated, which can be checked with `ll;pp` and a symlink should exist on `~/.bashrc`. In the **Files&Termux** app, the `ip` contents can then be checked by the path `~/i`. Are the plugins: **X11** and **widget** installed, the **widget** _table_ and the **X11** icon can be placed on the start screen (should now be complete). At the bottom is the **ExtraKeys** line that can be changed by `u ky` until it matches the Shot2.
- 3 Setting up the bookmark "Termux" (only once). Previously (Shot2), `Xvnc` start with the _password_ requeset/verify (six digits at least - only once). _Password_ is also needet for **RealVNC** - below. All required packedges are installed at the first start of a function by `bashrc **)`.
- 4 Here is the Window Manager WM=`fluxbox` started with an `aterm`, the KB is _not_ turned _on_ the Mouse-Buttons are _on_ and the menu _could_ open by taping the green circle at the top right. In `aterm` is `touch.exe` startet with `t t` (same as tap on touch in **widget** table). This XClient also changes the wallpaper with the file: `bg1.jpg`, which can also be edited with the **Foto-App** when the last entry in the **widget** table (`view*`) is used.

`**)`. I recommend using `bashrc` unchanged, which corresponds to the `Xwayland,fluxbox` start and to create the fourth Shot with tap on `aterm-VNC` in the **widget** table (first).
### Further steps to check process and start _compare apps:
Here `nano` (simple editor and part of **Termux** bootstrap) ist used and **RealVNC** app is installed
![grafik](https://user-images.githubusercontent.com/45426380/144202053-932d1e8d-5646-45dd-83b6-8708fb31db86.png)
- Shot1 With AVD emulator, split areas are possible, so that the two **widget** tap actions are displayed in different areas of the screens. Top `nano-bashrc` (reduced in Termux with pinch to see everything) and `aterm-VNC` in **MultiVNC** (command in Termux marked and could with "Copy" put in the Android clipboard). It is possible in both Apps terminals to use KB/command, which allows manual start (`t 3` for Shot2). Between the split areas, the _ExtraKeys_ (EK part of Termux top) can be seen and instead of EK has **MultiVNC** the green circle.
- Shot2 is the registration in **RealVNC** with _**one**_ address field and the same password (here with floating KB) as before. This is opened with `t 3` in one of the terminals (Shot1), but stops the split mode (restriction of **RealVNC**). The apps can then only be used successively or with **float** (Termux) in:
- Shot3 with KB+ExtraKeys of **RealVNC** and with `touch-700x1400` of Xclient `touch.exe` (see below on Huawei). In the **float** app, the XClient: `aterm` was started with `t :1 x` and displays the process list in this with the alias `pp`.
- Shot4 shows the KB of the Float app (without EK) and the emulated mouse buttons of **RealVNC** - with mouseweel (right). This option is missing at Multivnc, but would not be necessary with extrakeys.

Two last Shots with the **float** app on Huawei. They show the **X11** and **MultiVNC** app with XClient `touch.exe` (twice) in Portrait and Landscape. It's not here about "float bugs", so only the hint that this app has some: no EK, "double" zoom/pinch not on AVD and displacement restrictions. `touch.exe` (managed _with_ wallpaper three Windows) is started in **X11** (`:0`) with WM=`fuxbox` (managed _also_ wallpaper) and in **MultiVNC** (`:1`) without WM. In Split mode, both apps are visible, but in contrast to **RealVNC** (one `Xvnc` for both *VNC) different RS=Reseed Screens. The **X11**-RS is also changed with rotation or split position.
![grafik](https://user-images.githubusercontent.com/45426380/144202539-8073b4ad-31e5-4201-89f7-834cb977ec45.png)
When I try to start both VNC clients, the `Xvnc` process crash on my Device - Your too?
### To the bugs in this Arch: X86 (no multitouch behavior)
The WM and also **X11** is _not_ necessary but helpful. As XClient suffices aterm but the alternative **RealVNC** is needed for check. _Multitouch_ is an emulated function at AVD, which allows a maximum of two touches as follows: With SHIFT (hold) and mouse move, the middle position is posierted on the screen and then fixed with CTRL (hold). With the following mouse moves, the middle position is displayed two "fingers" and can be moved to the position with which the _Multitouch_ action starts (mouse click). Depending on the app, usually different _"zoom" are done_ actions.

In **Termux**, the font size varies (not ExtraKeys). In **RealVNC**, the Reseed Screen is scaled (reduces up to the largest full display without screen _shift_). **Fotos** makes the same. In **X11**, the XClients treat _multi-touch_ when designed for it. Only **MultiVNC** does (here) _**nothing**_ except _single mouse_ actions. The Apps are used in _split_ mode and rotated. Here is a video to show that:

https://user-images.githubusercontent.com/45426380/142216271-606d76de-9a87-4e53-b530-67fcf01d6acc.mp4

Reseed Screen=**RS** (everything visible and _mouse mode_ works) is not possible with **MultiVNC** for two reasons:
- Zoom dosn't work and if it's work (Oher devices) is limited to min 50/75% reduction - taskbar is never visible (below)
- Mouse Buttom and green circle Menue coveres important parts on Xclients (here `fluxbox,aterm` and `touch`)

Exception: **RealVNC** works **only** _fullscreen_ and scale to **RS** is always possible here. Continuation Video session:

https://user-images.githubusercontent.com/45426380/142219999-3866d306-40f4-4135-a5b1-eb36b7d63cfe.mp4

**Comment by RalfWerner** [comment]
- No graphic on arm device
- No multi-touch on AVD (Android Virtual Device)

**Comment by nagasawa** [comment]
@RalfWerner
There is an X11Server for termux, so please use that.
https://github.com/nagasawa/termux-tools/wiki

**Comment by RalfWerner** [comment]
>There is an X11Server for termux, so please use that.

That's right and two versions are included in [ip.zip](https://www.dropbox.com/s/ug071qoox8gwf1c/ip.zip?dl=0) (for comparison). Your [link](https://github.com/nagasawa/termux-tools/wiki) is probably version X11_02.06 (without **EK** and fullscreen) or did you _merge_ the benefits of different versions/branches?

**Comment by bk138** [comment]
> > That's a lot of info - can you please summarize in a few words what exactly is not working?
> 
>     * No graphic on arm device (black screen with green circle and mouse buttons) I have the same effect with TightVNC on a Windows PC as VNC server and the attempt with this Android device to build a session to the PC (control:**Yes**, view:**No**).

I suspect the device is at fault here, feel free to try a different VNC viewer app, [aVNC](https://github.com/gujjwal00/avnc) for instance, and see if the problem happens there as well. 

> 
>     * No multi-touch on AVD (Android Virtual Device) see above [here](https://user-images.githubusercontent.com/45426380/142216271-606d76de-9a87-4e53-b530-67fcf01d6acc.mp4) and how it [should](https://user-images.githubusercontent.com/45426380/142219999-3866d306-40f4-4135-a5b1-eb36b7d63cfe.mp4) be

AVD is a non-target for me, thus I do not intend to work on this.

**Comment by RalfWerner** [comment]
> I suspect the device is at fault here, feel free to try a different VNC viewer app, aVNC for instance, and see if the problem happens there as well.

**MultiVNC** is the only VNC client, from those I checked where the problem occurs on this device - or with **RealVNC** works everything (with the known limitations of this tool).
> AVD is a non-target for me, thus I do not intend to work on this.

We can set the AVD topic aside, especially as other VNC clients do _**not have the problem**_ (see last video above). On the other hand, in this issue, the _**"Steps to Repeat"**_ are described, which are required for #169 too and they can be used as well on any other Android device.
But you can let tiis issue closed, because there is a reference inside and if no solution is to be expected here.
