### ISSUE TITLE
Uppercase letters and symbols not working

### ISSUE THREAD

**Issue by k2helix** [bk138/multivnc#180]
**Is your bug report about the Desktop Multivnc or the Mobile Multivnc?**
Android

**Which MultiVNC version are you using?**
2.0.4

**Describe the bug**
When using capital letters and symbols like @ in the app (which I need for the email and the password of some websites), they are not recognized. I have tried with other vnc apps and it worked.

**To Reproduce**
1. Open MultiVNC
2. Connect to some server
3. Use the keyboard in any input field
4. Capital letters and symbols like @ simply do not work.

**Expected Behavior**
These characters should work.

**For the Mobile Version (please complete the following information):**
 - Android version: Android 11 (LineageOS 18.1)
 - Installed from Play Store, F-Droid, Amazon Appstore: F-Droid

**Comment by bk138** [comment]
Thanks for reporting! What language settings are you using on server and client side?

**Comment by k2helix** [comment]
> Thanks for reporting! What language settings are you using on server and client side? Also, the client side keyboard app is interesting.

Hi! If you mean my device language, it is English. My keyboard is OpenBoard.

**Comment by bk138** [comment]
Just asking so I can repro as closely as possible. So you're connecting from an Android device with English locale with OpenBoard keyboard - what's on the server side? Sorry I should update the bug template...

**Comment by k2helix** [comment]
> Just asking so I can repro as closely as possible. So you're connecting from an Android device with English locale with OpenBoard keyboard - what's on the server side? Sorry I should update the bug template...

The server is in English too. I do not think this is the problem, as I said I already tested with other vnc apps and it worked, but I think multivnc is really better in terms of usability.

**Comment by Oxreim** [comment]
I am able to reproduce this issue from an android device on Debian Ubuntu, Fedora, CentOS, and OpenSuse hosts running virtual machines via qemu/kvm or libvirts built in vnc server. I am unsure how to better identify the version. Other android vnc clients such as AVNC work without issue and desktop VNC clients so i think the issue lies in multivnc.

If it would help i could setup a host environment that i see the issue against for testing purposes.

**Comment by gujjwal00** [comment]
@bk138  I think we are missing Shift key conversion [here](https://github.com/bk138/multivnc/blob/baf2aa0ce3bff081e17ef3a93f5dd1287232f62e/android/app/src/main/java/com/coboltforge/dontmind/multivnc/VNCConn.java#L554-L586), hence MultiVNC is sending 0 (`NoSymbol`) for Shift key events. I can reproduce the issue with TigerVNC (although Vino is working), and if I add the [conversion](https://github.com/gujjwal00/multivnc/commit/8c39fd2e7500538f88f589ee0f98ac7cc942659e), it starts working correctly.

**Comment by bk138** [comment]
> @bk138 I think we are missing Shift key conversion [here](https://github.com/bk138/multivnc/blob/baf2aa0ce3bff081e17ef3a93f5dd1287232f62e/android/app/src/main/java/com/coboltforge/dontmind/multivnc/VNCConn.java#L554-L586), hence MultiVNC is sending 0 (`NoSymbol`) for Shift key events. I can reproduce the issue with TigerVNC (although Vino is working), and if I add the [conversion](https://github.com/gujjwal00/multivnc/commit/8c39fd2e7500538f88f589ee0f98ac7cc942659e), it starts working correctly.

Cherry-picked, thanks so much!
