### ISSUE TITLE
Zooming broken on Android 12

### ISSUE THREAD

**Issue by MrPeteH** [bk138/multivnc#183]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 - Mobile (Android):

**Which MultiVNC version are you using?**
2.0.5

**Which server are you connecting to?**
 - VNC server vendor: TightVNC
 - VNC server version: 2.8.63.0
 - OS version: Win10
 - OS language: English

Maybe important: 
 - host resolution: 3840 x 1197 (two side by side screens)
 - viewer resolution: 2863 x 1440 (500 dpi!)

**Describe the bug**
MultiVNC is unusable due to large white rectangles that overlay the screen. 
- On the left, top to bottom (of the viewer window... far beyond the server viewport)
- On top, left to right of the viewer window...
- If I zoom in and attempt to scroll, I also see them bottom and right

If I had to guess, 
- There may be code... attempting to "frame" what I see
- But it is not done correctly. A miscalculation of viewport vs window?
- I also note that the virtual mouse is always misaligned... and the misalignment depends on the current zoom level

**To Reproduce**

**For the Mobile Version (please complete the following information):**
 - Android version: 12
 - Installed from Play Store

**Additional context**
![2022-02-08 14 04 04](https://user-images.githubusercontent.com/3031550/153075489-1b2f3d5e-b507-494d-a002-2980ddbff43f.jpg)
![2022-02-08 14 02 34](https://user-images.githubusercontent.com/3031550/153075523-7b3164eb-55e8-4b96-a07e-df35df040ac8.jpg)

**Comment by MrPeteH** [comment]
Does not happen on any other viewer I've tried (I've tried several, including freebVNC)

I'll work on the latter test :)

**Comment by bk138** [comment]
@MrPeteH nevermind, I can repro this on a Galaxy S10.

**Comment by bk138** [comment]
Might be limitations of [glTexImage2D](https://github.com/bk138/multivnc/blob/master/android/app/src/main/cpp/vnccanvas.c#L27), but AVNC does it [similarly](https://github.com/gujjwal00/avnc/blob/master/app/src/main/cpp/native-vnc.cpp#L495)... :thinking:

**Comment by MrPeteH** [comment]
S10e does not have the issue.
Viewer 1080x2020 at 480 dpi.

So far more a resolution than dpi thing...

**Comment by bk138** [comment]
This actually happens with every server resolution on my device now. I can state it worked before, so it's likely the recent update to Android 12 that changed something...

**Comment by bk138** [comment]
If I remove [`VncCanvas.scrollToAbsolute()`](https://github.com/bk138/multivnc/blob/master/android/app/src/main/java/com/coboltforge/dontmind/multivnc/VncCanvas.java#L432), it works on Android 12 again. Will test with other devices the next days...

**Comment by bk138** [comment]
# test results
## v2.0.5
* Samsung S10e w/ Android 12: :lady_beetle: 
* Samsung Tab A w/ Android 11: :ok: 
* Samsung S20FE w/ Android 11: :ok:

**Comment by MrPeteH** [comment]
Yep. Fixed. Now I can see the next issue more clearly 🤠
