### ISSUE TITLE
No bookmarks found for widget

### ISSUE THREAD

**Issue by ChemoCosmo** [bk138/multivnc#184]
When creating a new widget, it says No bookmarks found, even though there are two bookmarks defined.

Version 2.0.5

![Screenshot_20220212-115730_MultiVNC](https://user-images.githubusercontent.com/58092307/153708826-428b1c7e-77b0-4b02-a13b-dd0554d116b0.png)

![Screenshot_20220212-115801_MultiVNC](https://user-images.githubusercontent.com/58092307/153708832-168bcf40-9b42-4de5-ba20-5a5a97d030a2.png)

Reproducing:
1) Long Tap at Main screen
2) Select MultiVNC Widget from Widget list
3) Get Empty Bookmark list

**Comment by bk138** [comment]
Alright, can repro. Thanks for this very good report!

**Comment by ChemoCosmo** [comment]
Great! 

This is a rather exotic android distribution: e/OS Q 0.21-q (Android 10) 
On a Fairphone 3

**Comment by bk138** [comment]
Fix will be in next release.

**Comment by ChemoCosmo** [comment]
Thanks for the fix! Works like a charm!!

**Comment by bk138** [comment]
> Thanks for the fix! Works like a charm!!

Thanks for the thanks! Always happy about a 5-star store rating, GitHub stars or a small donation :-)
