### ISSUE TITLE
FR: option to make all touch events silent

### ISSUE THREAD

**Issue by AtmanActive** [bk138/multivnc#185]
**Is your feature request about the Desktop Multivnc or the Mobile MultiVNC?**
 - Mobile (Android):
 - installed from F-Droid:

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm clicking around using on-screen left/middle/right buttons and my phone goes click, click, click and does the haptic vibration

**Describe the solution you'd like**
I would like to be able to disable all sounds and haptic feedback for all buttons either on an application level, or, alternately, per server.

**Describe alternatives you've considered**
Putting my phone into do-not-disturb mode, but haptic feedback vibration is still present.

**Additional context**
I have a high myopia (shortsightedness) which enables me to look at a 6" phone screen (without my glasses) in 2560x1080 resolution and still be able to read every single letter from a normal windows desktop. In other words, I have a microscopic eyesight. This serves me pretty well for controlling my desktop from my android phone, but, since I am holding my phone some 5cm away from my eyes, all sounds and vibrations are disturbing me. Also, when I use MultiVNC in this way, I use it to do some real work, not just for an occasional click here and there. I'm doing everything as if I'm in front of my desktop. That means a lot of clicking and a lot of dragging (button holding), and, in all of this, current sound and haptic feedback are just annoying me. I believe I would be much faster with MultiVNC if all clicks/drags were silent.
As some people could find that click sound/vibro useful (in some other usage scenarios), then, the best thing to do, IMHO, is to make it optional.

**Comment by bk138** [comment]
@AtmanActive turns out the implementation overrode the system settings. This has been removed. I was able to toggle click sounds and haptic feedback via the procedure outlined in https://www.howtogeek.com/262032/how-to-disable-haptic-feedback-or-vibrate-on-tap-in-android/

**Comment by AtmanActive** [comment]
Thanks for letting me know.
Unfortunately, it doesn't work here on Android 12 and MultiVNC v2.0.10. Do I need an updated MultiVNC version? Where could I get one?
Thanks!

**Comment by bk138** [comment]
> Thanks for letting me know. Unfortunately, it doesn't work here on Android 12 and MultiVNC v2.0.10. Do I need an updated MultiVNC version? Where could I get one? Thanks!

This will be in v2.1.0 which is due to be released very soon, hopefully today.
