### ISSUE TITLE
AltGr key not working

### ISSUE THREAD

**Issue by anonimo82** [bk138/multivnc#197]
**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android): Android

**Which MultiVNC version are you using?**
2.0.7

**Which server are you connecting to?**
 - VNC server vendor:unknown
 - VNC server version:unknown 
 - OS version:unknown 
 - OS language:unknown 

**Describe the bug**

The AltGr key doesn't work as expected

**To Reproduce**
Press AltGr+E, the € symbol doesn't appear (just an example) 

**Expected Behavior**
The € symbol should be typed

**Screenshots**
no

**For the Desktop Version (please complete the following information):**
 - OS and version:
 - Xorg version used:
 - Wayland version used:

**For the Mobile Version (please complete the following information):**
 - Android version:Android Q
 - Installed from Play Store, F-Droid, Amazon Appstore:Play Store

**Additional context**

none

**Comment by bk138** [comment]
Hm, seems you already reported this as #182 :-)
