### ISSUE TITLE
Submit app to F-Droid

### ISSUE THREAD

**Issue by JohnVeness** [bk138/multivnc#2]
It would be great if this app was available via the F-Droid repository (https://f-droid.org/) in addition to Google Play Store. This is useful for people who don't like to use Google Play Store in general.

Also, F-Droid creates an archive of previous versions, something that Google Play does not do. This can be useful if there is a bug in a new version, allowing the user to revert to an older one.

**Comment by bk138** [comment]
current state at https://gitlab.com/bk138/fdroiddata/commits/multivnc fails building locally as my gradle version seems to be too old.

**Comment by bk138** [comment]
https://blog.fossasia.org/setting-up-environment-to-build-pslab-android-app-using-fdroid-build/

**Comment by bk138** [comment]
MR tracked here: https://gitlab.com/fdroid/fdroiddata/merge_requests/4327
