### ISSUE TITLE
Your website is SLOW and confusing

### ISSUE THREAD

**Issue by ELY3M** [bk138/multivnc#203]
those ads is really misleading.... :(   I cant find download for this app.  
I will just walk away.....      

put your app release in release section on your repo.

**Comment by gujjwal00** [comment]
For a second I was like 'what is this guy smoking?' 😀. Then I realized OP might be be tallking about old SourceForge repo, which is still the first result for 'multivnc' search on DDG.

So @ELY3M, can you please link the website you were on?

**Comment by bk138** [comment]
> put your app release in release section on your repo.

Referring to https://github.com/bk138/multivnc/releases/tag/AndroidMultiVNC-2.0.10 @ELY3M ?
