### ISSUE TITLE
BackSpace and AltGr not recognized

### ISSUE THREAD

**Issue by ibox0** [bk138/multivnc#204]
**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android):
Bug verified in MultiVnc for Android version 2.0.10 , using Samsung Dex from Samsung Galaxy S8 (Android 9) 

**Which MultiVNC version are you using?**
2.0.10
**Which server are you connecting to?**
 - VNC server vendor:
TigerVNC 
- VNC server version:
1.10.1  (on ubuntu)
1.9  (on debian)
 - OS version:
Ubuntu 20.04.5 LTS - Linux janux 5.4.0-125-generic , Desktop KDE 5.68  
Ubuntu 10 (raspbian)
- OS language:
English, Desktop set in Italian or in English

**Describe the bug**
Problem1:
  The "Backspace" of the keyboard is not recognized by the vnc session.
  Xev does not produce any output when Backspace is pressed 

Problem2:
   The AltGr+@ (in italian keyboard this is the key combination to get the @, but the same applies to other like curly or square brackets) is not working. The @ is not shown and the "Alt" status becomes "sticky" , eg after the combination is pressed all characters are interpreted as Alt+char (eg hitting space without Alt opens the window menu). To restore from that the Shift+Alt must be pressed.

In both scenarios, the keys are properly interpreted by other Android applications of the client

UPDATE: the bug seems to be related to some odd behavior of the key autorepeat function .... when  enabled, all the keys gets duplicated while backspace is working properly, when disabled the keys are ok (non duplicated) but the backspace is apparently not working but can be activated after a very long press (keep it pressed for many seconds, repeat with high frequency keyup and keydown) ... when "activated", it works well until another char is pressed, then the behavior repeats ...     

**To Reproduce**
Try to use Backspace or AltGr+@ ...
for BackSpace, nothing to show.
For AltGr+, the xev output follows
Outer window is 0x1a00001, inner window is 0x1a00002

PropertyNotify event, serial 8, synthetic NO, window 0x1a00001,
    atom 0x27 (WM_NAME), time 1197068663, state PropertyNewValue

PropertyNotify event, serial 9, synthetic NO, window 0x1a00001,
    atom 0x22 (WM_COMMAND), time 1197068663, state PropertyNewValue

PropertyNotify event, serial 10, synthetic NO, window 0x1a00001,
    atom 0x28 (WM_NORMAL_HINTS), time 1197068663, state PropertyNewValue

CreateNotify event, serial 11, synthetic NO, window 0x1a00001,
    parent 0x1a00001, window 0x1a00002, (10,10), width 50, height 50
border_width 4, override NO

PropertyNotify event, serial 14, synthetic NO, window 0x1a00001,
    atom 0xf7 (WM_PROTOCOLS), time 1197068664, state PropertyNewValue

MapNotify event, serial 15, synthetic NO, window 0x1a00001,
    event 0x1a00001, window 0x1a00002, override NO

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x13e (_NET_WM_VISIBLE_NAME), time 1197068665, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x13f (_NET_WM_VISIBLE_ICON_NAME), time 1197068665, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x165 (_OB_APP_ROLE), time 1197068665, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x167 (_OB_APP_NAME), time 1197068665, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x168 (_OB_APP_CLASS), time 1197068665, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x169 (_OB_APP_GROUP_NAME), time 1197068665, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x16a (_OB_APP_GROUP_CLASS), time 1197068665, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x166 (_OB_APP_TITLE), time 1197068665, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x16b (_OB_APP_TYPE), time 1197068665, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x100 (_NET_WM_ICON), time 1197068666, state PropertyNewValue

ReparentNotify event, serial 18, synthetic NO, window 0x1a00001,
    event 0x1a00001, window 0x1a00001, parent 0xa011ed,
    (0,0), override NO

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x105 (_NET_WM_STATE), time 1197068667, state PropertyNewValue

ConfigureNotify event, serial 18, synthetic NO, window 0x1a00001,
    event 0x1a00001, window 0x1a00001, (0,0), width 178, height 178,
    border_width 0, above 0xa01239, override NO

ConfigureNotify event, serial 18, synthetic NO, window 0x1a00001,
    event 0x1a00001, window 0x1a00001, (2,30), width 178, height 178,
    border_width 0, above 0xa01239, override NO

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0xfc (_NET_FRAME_EXTENTS), time 1197068667, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x145 (_KDE_NET_WM_FRAME_STRUT), time 1197068667, state PropertyNewValue

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x143 (_NET_WM_ALLOWED_ACTIONS), time 1197068667, state PropertyNewValue

ConfigureNotify event, serial 18, synthetic YES, window 0x1a00001,
    event 0x1a00001, window 0x1a00001, (453,462), width 178, height 178,
    border_width 2, above 0x0, override NO

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0xff (_NET_WM_DESKTOP), time 1197068668, state PropertyNewValue

MapNotify event, serial 18, synthetic NO, window 0x1a00001,
    event 0x1a00001, window 0x1a00001, override NO

VisibilityNotify event, serial 18, synthetic NO, window 0x1a00001,
    state VisibilityUnobscured

Expose event, serial 18, synthetic NO, window 0x1a00001,
    (0,0), width 178, height 10, count 3

Expose event, serial 18, synthetic NO, window 0x1a00001,
    (0,10), width 10, height 58, count 2

Expose event, serial 18, synthetic NO, window 0x1a00001,
    (68,10), width 110, height 58, count 1

Expose event, serial 18, synthetic NO, window 0x1a00001,
    (0,68), width 178, height 110, count 0

PropertyNotify event, serial 18, synthetic NO, window 0x1a00001,
    atom 0x128 (WM_STATE), time 1197068671, state PropertyNewValue

EnterNotify event, serial 18, synthetic NO, window 0x1a00001,
    root 0x395, subw 0x0, time 1197068671, (88,74), root:(543,538),
    mode NotifyNormal, detail NotifyNonlinear, same_screen YES,
    focus NO, state 0

KeymapNotify event, serial 18, synthetic NO, window 0x0,
    keys:  162 0   0   0   16  0   64  0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

FocusIn event, serial 18, synthetic NO, window 0x1a00001,
    mode NotifyNormal, detail NotifyNonlinear

KeymapNotify event, serial 18, synthetic NO, window 0x0,
    keys:  199 0   0   0   16  0   64  0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

ColormapNotify event, serial 18, synthetic NO, window 0x1a00001,
    colormap 0x20, new NO, state ColormapInstalled

KeyRelease event, serial 44, synthetic NO, window 0x1a00001,
    root 0x395, subw 0x0, time 1197068734, (88,74), root:(543,538),
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
    XLookupString gives 1 bytes: (0d) "
"
    XFilterEvent returns: False

KeyPress event, serial 47, synthetic NO, window 0x1a00001,
    root 0x395, subw 0x0, time 1197071054, (88,74), root:(543,538),
    state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 47, synthetic NO, window 0x1a00001,
    root 0x395, subw 0x0, time 1197071056, (88,74), root:(543,538),
    state 0x8, keycode 108 (keysym 0xffea, Alt_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 47, synthetic NO, window 0x1a00001,
    root 0x395, subw 0x0, time 1197071539, (88,74), root:(543,538),
    state 0x8, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 47, synthetic NO, window 0x1a00001,
    root 0x395, subw 0x0, time 1197071540, (88,74), root:(543,538),
    state 0x9, keycode 11 (keysym 0x40, at), same_screen YES,
    XLookupString gives 1 bytes: (40) "@"
    XmbLookupString gives 1 bytes: (40) "@"
    XFilterEvent returns: False

KeyRelease event, serial 47, synthetic NO, window 0x1a00001,
    root 0x395, subw 0x0, time 1197071541, (88,74), root:(543,538),
    state 0x9, keycode 11 (keysym 0x40, at), same_screen YES,
    XLookupString gives 1 bytes: (40) "@"
    XFilterEvent returns: False

KeyRelease event, serial 47, synthetic NO, window 0x1a00001,
    root 0x395, subw 0x0, time 1197071541, (88,74), root:(543,538),
    state 0x9, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 47, synthetic NO, window 0x1a00001,
    root 0x395, subw 0x0, time 1197071820, (88,74), root:(543,538),
    state 0x8, keycode 108 (keysym 0xffea, Alt_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

**Expected Behavior**
Backspace and AltGr+char shall be properly recognized and managed

**Screenshots**
none

**For the Desktop Version (please complete the following information):**
NA

**For the Mobile Version (please complete the following information):**
 - Android version: 9
 - Installed from Play Store
  
**Additional context**
NA

**Comment by bk138** [comment]
Looks like a duplicate and extension of #182, I'm adding the backspace info there and closing this one. Please re-open if this is not the same as #182 .
