### ISSUE TITLE
in Windows 11 of Ubuntu22.04

### ISSUE THREAD

**Issue by qq805005062** [bk138/multivnc#206]
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  libwxservdisc/src/CMakeLists.txt:20 (find_package)

**Comment by bk138** [comment]
Please be so kind and write a bug report with what you're trying to do, what happens and your exact setup.

**Comment by bk138** [comment]
Closing due to no answer.
