### ISSUE TITLE
just below horrible as far useability . 

### ISSUE THREAD

**Issue by LoonKiller** [bk138/multivnc#208]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android):  Kindle 2022 

**Which MultiVNC version are you using?**
  whatever is installed for kindle 2022 

**Which server are you connecting to?**
 - VNC server vendor:
 - VNC server version:
 - OS version:
 - OS language:

**Describe the bug**
 The constant switching between "keyboard " and " mouse ". ..is exhausting..

Why can't it work like WYSIWYG ??  Tap for keyboard ,  double tap for mouse or special keys

**To Reproduce**

**Expected Behavior**
. Other VNC clients for older Kindled prior to 2022 work better . This is downright annoying and horrible to use 

**Screenshots**

**For the Desktop Version (please complete the following information):**
 - OS and version:
 - Xorg version used:
 - Wayland version used:

**For the Mobile Version (please complete the following information):**
 - Android version:
 - Installed from Play Store, F-Droid, Amazon Appstore:

**Additional context**

**Comment by bk138** [comment]
Just leaving a rant here will get you no changes to the app. Please stay polite.

**Comment by LoonKiller** [comment]
The current implementation with "toggle" menu choices makes it an  absolutely unusable product ..Being that it distributed with the  new Kindle 2022  , you should take reviews more seriously. But the world needs fast food workers too. 

Retired software engineer and product manager .

**Comment by bk138** [comment]
I'm not aware of the app being shipped per default on any OEM product. There hasn't been any customisation for Kindle devices AFAIK. You'd make conversation easier if you'd be more friendly. For the time being, maybe looking at https://github.com/bk138/multivnc/projects/2 might help you a bit.
