### ISSUE TITLE
Android: Physical middle mouse clicks do not work

### ISSUE THREAD

**Issue by TheEgghead27** [bk138/multivnc#209]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 - Mobile (Android):

**Which MultiVNC version are you using?**

2.0.10

**Which server are you connecting to?**
 - VNC server vendor: x11vnc
 - VNC server version: 0.9.16
 - OS version: Linux
 - OS language: en-us

**Describe the bug**
When a physical mouse is attached, clicking the middle mouse button emulates the home button (systemwide function).

**To Reproduce**
1. Pair/attach a physical mouse to an Android device
2. Open any VNC session in the app
3. Attempt to send a middle-mouse click to the host using your physical mouse
4. Get sent back to the home screen

**Expected Behavior**
The app might be able to override the system function so it can receive and relay the middle-mouse click input. A quick search on StackOverflow shows that [altering the manifest may allow it](https://stackoverflow.com/questions/36920892/disable-gotohome-behaviour-provided-by-a-mouse-middle-button-click-on-android), but I'm not experienced enough to tell whether this fix may cause other problems or not.

**Screenshots**
N/A

**For the Mobile Version (please complete the following information):**
 - Android version: 10
 - Installed from F-Droid

**Additional context**
Thank you so much for making such an awesome app! Appreciate all the work, and I wish I could donate!

**Comment by bk138** [comment]
Thanks for your feedback! This was reported before in #189 and fixed with #190, it will appear in v2.1.0. Are you OK to close this albeit the new version is not out yet?

**Comment by TheEgghead27** [comment]
Oh, neat! Sorry for not checking closed issues first! Great work!
