### ISSUE TITLE
Since Update 2.1.0: VNC connection failed!

### ISSUE THREAD

**Issue by Jokitsch** [bk138/multivnc#212]
**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
Mobile (Android)

**Which MultiVNC version are you using?**
MultiVNC version 2.1.0

**Describe the bug**
When I try to start a connection the message appears: "VNC connection failed! Only the original thread that created a view hierarchy can touch its views."
The connection works fine before the version was updated.

**For the Mobile Version (please complete the following information):**
Android version: 7.0
Installed from Play Store

**Comment by bk138** [comment]
Thanks for the report! Did you send a crash report up to Google?

**Comment by Jokitsch** [comment]
No, not yet. How can I do this? Is this a Google / Android problem?Best regardsJochenVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Christian Beier ***@***.***> Datum: 30.12.22  17:18  (GMT+01:00) An: bk138/multivnc ***@***.***> Cc: Jokitsch ***@***.***>, Author ***@***.***> Betreff: Re: [bk138/multivnc] Since Update 2.1.0: VNC connection failed! (Issue #212) 
Thanks for the report! Did you send a crash report up to Google?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/bk138/multivnc/issues/212#issuecomment-1367992530",
"url": "https://github.com/bk138/multivnc/issues/212#issuecomment-1367992530",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bk138** [comment]
Sorry, my bad, I misread your report. I think our best bet is to narrow down the change that might have caused that via [git bisect](https://git-scm.com/docs/git-bisect), which would mean me sending you a series of apks and you say "good" or "bad" until the change that caused this is found. Would that work for you?

**Comment by bk138** [comment]
@Jokitsch nevermind, I could repro this on an Android 7 emulator. v2.1.1 will be out in a few minutes.

**Comment by Jokitsch** [comment]
v2.1.1 works fine - perfect!!! Thx a lot :-)
