### ISSUE TITLE
[fr] reproducible F-Droid app

### ISSUE THREAD

**Issue by jindam-vani** [bk138/multivnc#215]
if possible can you please app reproducible F-Droid app. for details see [Towards a reproducible F-Droid](https://f-droid.org/en/2023/01/15/towards-a-reproducible-fdroid.html).

jindam, vani

**Comment by bk138** [comment]
Sure, we can try to add this. If you file a pull request, I think it would be happily merged.

**Comment by gujjwal00** [comment]
Please note that this is not possible for already published app. Enabling reproducible build will change signing key, unless you can somehow obtain current F-Droid key.

**Comment by bk138** [comment]
> Please note that this is not possible for already published app. Enabling reproducible build will change signing key, unless you can somehow obtain current F-Droid key.

Alright, thanks for the info! Closing then.

**Comment by gujjwal00** [comment]
Sorry, I may have remembered incorrectly:
- There is no way for existing app to change signing key
- The _is_ a way to have two APKs on F-Droid for each version - one signed by developer key, other by F-Droid key. But it doesn't support automatic updates.

But first hurdle is reproducible build. When listing AVNC on F-Droid, I tried to go this route, but could not get my APK to match with F-Droid. Main issue is native libraries, especially the SSL library.

**Comment by bk138** [comment]
Anyway, if someone steps up with a working version and a PR, this can be merged.

**Comment by eighthave** [comment]
You can enable reproducible builds for an existing app, there are two approaches on F-Droid with reproducible builds:

* only publish with the upstream signer
* publish both with the upstream signer and f-droid.org signer
