### ISSUE TITLE
Send mouse scroll / scrolling input

### ISSUE THREAD

**Issue by distinctjuggle** [bk138/multivnc#235]
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your feature request about the Desktop Multivnc or the Mobile MultiVNC?**
 - If Mobile, installed from Play Store or F-Droid: F-Droid

**Is your feature request related to a problem? Please describe.**
Scrolling is a pretty darn useful thing and it is hard to navigate some websites or perform some capabilities without it.  

**Describe the solution you'd like**
Some method of scrolling up or down, such as 2 or 3 finger input.

**Describe alternatives you've considered**
Using a different app entirely

**Additional context**
Is there a way to do this?  I've tried searching existing features, I've tried poking around in help menus and docs, but I haven't found a way.  If it is not implemented, I'd love to see it as a feature.

**Comment by bk138** [comment]
This can be done using the volume keys. I'll add that to the help screen.
