### ISSUE TITLE
Add Support for other Protocol e.g. RDP and Gamestream (Sunshine/Moonlight)

### ISSUE THREAD

**Issue by Mannshoch** [bk138/multivnc#243]
**Is your feature request about the Desktop Multivnc or the Mobile MultiVNC?**
 - Mobile (Android):
 - F-Droid:

**Is your feature request related to a problem? Please describe.**
There is no RDP player on fdroid.

**Describe the solution you'd like**
Let me enter an ip and MultiVNC checks which protocol work (on standard Ports) and prompt the possible connections.

**Describe alternatives you've considered**
RDP does not exist on fdroid

**Comment by bk138** [comment]
Won't add this in the foreseeable future. If I'll ever to a multi-protocol remote desktop client, it'll probably be a new project.
