### ISSUE TITLE
Compatibility issues - Android 12; version 2.1.5 (and 2.1.6 via Google Play)

### ISSUE THREAD

**Issue by JOs86** [bk138/multivnc#245]
Mobile (Android): Android 12
Version: 2.1.5, 2.1.6
HW: Samsung S10+ (Exynos 9820)
Model: SM-G975F
API: 31
One UI: 4.1
Google Play Services: 24.40.35
[2.1.6] Installed from Play Store, [2.1.5] from F-Droid

 - VNC server vendor: TigerVNC
 - VNC server version: 1.12.0+dfsg-8
 - OS version: Debian 12 (Bookworm) via proot-distro [and termux]
 - OS language: English (US)
 -  Xorg version used: 2:21.1.7-3+deb12u7

Issue / Description
- Compatibility issue on Android 12
- Message: Error! VNC connection setup failed!

To Reproduce
<!-- Steps to reproduce the behavior:
1. Go to F-Droid or Google Play
2. Install and update MultiVNC (see the version above, i.e. 2.1.5, resp. 2.1.6)
3. Follow the termux and proot documentation and proceed to establish a connection.
4. Assumptions: X11 is working, other VNC sulutions are working.
5. Configure MultiVNC and connect

Expected Behavior
Connection established and successful.

Additional context
Resolution change in Android settings might be part of the problem, simply changing it back does not necessarily solve the issue. However, other solutions (VNC or not) are working correctly.
Concerning the server -> Proot enviroment might be tricky and complex.
I.e. parameter -geometry, etc. =>
[In Termux]
export XDG_RUNTIME_DIR=${TMPDIR}
proot-distro login debian --user root --shared-tmp
[In Proot, i.e. proot-distro]
root@localhost:~# export XDG_RUNTIME_DIR=${TMPDIR} 
root@localhost:~# vncserver -geometry 1600x900 -xstartup /usr/bin/startxfce4 :0

Additional logs might be necessary to determine the exact cause due to complexity.

![Screenshot_20241017_131716](https://github.com/user-attachments/assets/812b7408-1641-4974-ab71-2d7375ab213d)

**Comment by JOs86** [comment]
![Screenshot_20241017_131716](https://github.com/user-attachments/assets/32e0d564-d2c3-4687-9dc5-98b9aea097f8)

**Comment by JOs86** [comment]
To Reproduce
<!-- Steps to reproduce the behavior:
1. Go to F-Droid or Google Play
2. Install and update MultiVNC (see the version above, i.e. 2.1.5, resp. 2.1.6)
3. Follow the termux and proot documentation and proceed to establish a connection.
4. Assumptions: X11 is working, other VNC sulutions are working.
5. Configure MultiVNC and connect

Expected Behavior
Connection established and successful.

**Comment by JOs86** [comment]
Steps to reproduce the behavior:
1. Go to F-Droid or Google Play
2. Install and update MultiVNC (see the version above, i.e. 2.1.5, resp. 2.1.6)
3. Follow the termux and proot documentation and proceed to establish a connection.
4. Assumptions: X11 is working, other VNC sulutions are working.
5. Configure MultiVNC and connect

Expected Behavior
Connection established and successful.

**Comment by JOs86** [comment]
Additional context
Resolution change in Android settings might be part of the problem, simply changing it back does not necessarily solve the issue. However, other solutions (VNC or not) are working correctly.
Concerning the server -> Proot enviroment might be tricky and complex.
I.e. parameter -geometry, etc. =>
[In Termux]
export XDG_RUNTIME_DIR=${TMPDIR}
proot-distro login debian --user root --shared-tmp
[In Proot, i.e. proot-distro]
root@localhost:~# export XDG_RUNTIME_DIR=${TMPDIR} 
root@localhost:~# vncserver -geometry 1600x900 -xstartup /usr/bin/startxfce4 :0

Additional logs might be necessary to determine the exact cause due to complexity.

**Comment by JOs86** [comment]
Other versions:
2.1.3 -> ok
2.1.4 -> mostly ok

**Comment by bk138** [comment]
Can repro, it's most likely due to an SSL change.

**Comment by JOs86** [comment]
Excellent, thanks a lot in advance..

**Comment by bk138** [comment]
# findings
* most likely due to the inadvertent libressl update in 52afd2d33694e488f0df6b0b32e0ab4d520a7e4f
* 13791e52090a0e846342b521c7aa59021bc89c0c is ok for instance

**Comment by aRTee42** [comment]
Just FYI, Android / F-Droid Multi-VNC V2.1.7 still has this bug (I reported duplicate 246). Based on the above discussion, I was under the impression that the fix should have been there, or am I misunderstanding things?

**Comment by bk138** [comment]
> Just FYI, Android / F-Droid Multi-VNC V2.1.7 still has this bug (I reported duplicate 246). Based on the above discussion, I was under the impression that the fix should have been there, or am I misunderstanding things?

v2.1.8 has the fix, see https://github.com/bk138/multivnc/blob/master/android/ChangeLog.md :-)

**Comment by aRTee42** [comment]
Thanks a lot, just waiting for F-Droid to offer the update.

**Comment by JOs86** [comment]
FYI: It worked for me.. (on Android 12)
