### ISSUE TITLE
VNC connection setup failed!

### ISSUE THREAD

**Issue by aRTee42** [bk138/multivnc#246]
**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 Android

**Which MultiVNC version are you using?**
Version 2.1.6, this issue was also there on 2.1.5.

**Which server are you connecting to?**
 The connection failed error occurs when trying to connect to Tiger VNC server on Linux, Mageia and Manjaro.
However, it doesn't occur when connecting to the KDE desktop sharing feature (krfb?) (display :0 i.e. graphical desktop in that machine) on Mageia. 
Version 2.1.4 from late 2023 works with all of my VNC sessions.

**Describe the bug**
Instead of the desktop I just get the error message: 
"VNC connection setup failed!"

**To Reproduce**
Connect to any of the configured connections, or create a new one. With a new one or a memorized one with password, the error is shown before the password is requested.

**Expected Behavior**
Either the password prompt should be shown, or if the password is saved, the VNC session should be shown.

**Screenshots**
See screenshot

**For the Desktop Version (please complete the following information):**
n/a

**For the Mobile Version (please complete the following information):**
 - Android version: 14
 - Installed from F-Droid.

**Additional context**
I'll be going back to 2.1.4, can't do without this working.
If you have any apk to try out, no problem, just let me know. 
Thanks for this great app.
![Screenshot_20241019_093600](https://github.com/user-attachments/assets/f8abf742-801c-4d10-93fb-eab44fae04f4)

**Comment by bk138** [comment]
This has already been reported as #245, please subscribe there :-)

**Comment by aRTee42** [comment]
Sorry for the duplicate, I searched for this bug a few days ago, but only just got around to writing the report. Glad to find it's on the list, thanks.
