### ISSUE TITLE
server did not offer supported security type

### ISSUE THREAD

**Issue by Mannshoch** [bk138/multivnc#25]
Get every time the error "server did not offer supported security type"
But vnc work on ever other pc.

**Comment by bk138** [comment]
Hi! Can you please describe with what exact version of MultiVNC you are trying to connec to which server software running on which OS?

**Comment by Mannshoch** [comment]
MultiVNC 1.7.9
Ubuntu  18.04
Gnome VNC server: vino-server

**Comment by bk138** [comment]
Thanks! What version of vino is that and which auth methods are you using? A screenshot of the vino's preference widget would be helpful :-)

**Comment by Mannshoch** [comment]
good Question. Do you know where I could get these settings?
Normally I simply start the server and every thing works.

**Comment by bk138** [comment]
This is what they look like on Debian Buster:

![Bildschirmfoto von 2019-08-28 13-23-22](https://user-images.githubusercontent.com/80450/63851912-6a2ba280-c997-11e9-8ad9-8b994f63909a.png)

**Comment by Mannshoch** [comment]
It's looks the same except the password.

**Comment by bk138** [comment]
Confirming that it also does not work for me. This will work when we change the underlying VNC engine, progress is tracked in #17. I am closing this one in favour of #17.
