### ISSUE TITLE
Doesn't work with turbo vnc

### ISSUE THREAD

**Issue by kolay-v** [bk138/multivnc#26]
Version 1.7.9 f-droid
Show error when connecting `Unknown RFB message type 145`
Works with other vnc servers. 
Also tight vnc client connects just fine

**Comment by bk138** [comment]
Not in the official spec: https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#id58

**Comment by bk138** [comment]
https://sourceforge.net/p/virtualgl/mailman/message/31334795/ related?

**Comment by bk138** [comment]
@kolay-v what's your TurboVNC version?

**Comment by kolay-v** [comment]
TurboVNC Server v2.2.2 (build 20190522)

**Comment by bk138** [comment]
Confirmed. This will work with version 2.0. Progress of this is tracked in #17. 

Closing this one in favour of #17, feel free to upvote there and sry that it doesn't work for you right now.
