### ISSUE TITLE
-multiptr is  *** unrecognized option(s) ***

### ISSUE THREAD

**Issue by lx93** [bk138/multivnc#27]
05/09/2019 16:04:00 passing arg to libvncserver: -multiptr
###############################################################
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#@                                                           @#
#@  **  WARNING  **  WARNING  **  WARNING  **  WARNING  **   @#
#@                                                           @#
#@        YOU ARE RUNNING X11VNC WITHOUT A PASSWORD!!        @#
#@                                                           @#
#@  This means anyone with network access to this computer   @#
#@  may be able to view and control your desktop.            @#
#@                                                           @#
#@ >>> If you did not mean to do this Press CTRL-C now!! <<< @#
#@                                                           @#
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
#@                                                           @#
#@  You can create an x11vnc password file by running:       @#
#@                                                           @#
#@       x11vnc -storepasswd password /path/to/passfile      @#
#@  or   x11vnc -storepasswd /path/to/passfile               @#
#@  or   x11vnc -storepasswd                                 @#
#@                                                           @#
#@  (the last one will use ~/.vnc/passwd)                    @#
#@                                                           @#
#@  and then starting x11vnc via:                            @#
#@                                                           @#
#@      x11vnc -rfbauth /path/to/passfile                    @#
#@                                                           @#
#@  an existing ~/.vnc/passwd file from another VNC          @#
#@  application will work fine too.                          @#
#@                                                           @#
#@  You can also use the -passwdfile or -passwd options.     @#
#@  (note -passwd is unsafe if local users are not trusted)  @#
#@                                                           @#
#@  Make sure any -rfbauth and -passwdfile password files    @#
#@  cannot be read by untrusted users.                       @#
#@                                                           @#
#@  Use x11vnc -usepw to automatically use your              @#
#@  ~/.vnc/passwd or ~/.vnc/passwdfile password files.       @#
#@  (and prompt you to create ~/.vnc/passwd if neither       @#
#@  file exists.)  Under -usepw, x11vnc will exit if it      @#
#@  cannot find a password to use.                           @#
#@                                                           @#
#@                                                           @#
#@  Even with a password, the subsequent VNC traffic is      @#
#@  sent in the clear.  Consider tunnelling via ssh(1):      @#
#@                                                           @#
#@    http://www.karlrunge.com/x11vnc/#tunnelling            @#
#@                                                           @#
#@  Or using the x11vnc SSL options: -ssl and -stunnel       @#
#@                                                           @#
#@  Please Read the documention for more info about          @#
#@  passwords, security, and encryption.                     @#
#@                                                           @#
#@    http://www.karlrunge.com/x11vnc/faq.html#faq-passwd    @#
#@                                                           @#
#@  To disable this warning use the -nopw option, or put     @#
#@  'nopw' on a line in your ~/.x11vncrc file.               @#
#@                                                           @#
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
###############################################################
05/09/2019 16:04:01 x11vnc version: 0.9.15 lastmod: 2018-02-04  pid: 12962
05/09/2019 16:04:01 Using X display :0
05/09/2019 16:04:01 rootwin: 0x169 reswin: 0x3e00001 dpy: 0xfe543f50
05/09/2019 16:04:01 
05/09/2019 16:04:01 ------------------ USEFUL INFORMATION ------------------
05/09/2019 16:04:01 X DAMAGE available on display, using it for polling hints.
05/09/2019 16:04:01   To disable this behavior use: '-noxdamage'
05/09/2019 16:04:01 
05/09/2019 16:04:01   Most compositing window managers like 'compiz' or 'beryl'
05/09/2019 16:04:01   cause X DAMAGE to fail, and so you may not see any screen
05/09/2019 16:04:01   updates via VNC.  Either disable 'compiz' (recommended) or
05/09/2019 16:04:01   supply the x11vnc '-noxdamage' command line option.
05/09/2019 16:04:01 
05/09/2019 16:04:01 Wireframing: -wireframe mode is in effect for window moves.
05/09/2019 16:04:01   If this yields undesired behavior (poor response, painting
05/09/2019 16:04:01   errors, etc) it may be disabled:
05/09/2019 16:04:01    - use '-nowf' to disable wireframing completely.
05/09/2019 16:04:01    - use '-nowcr' to disable the Copy Rectangle after the
05/09/2019 16:04:01      moved window is released in the new position.
05/09/2019 16:04:01   Also see the -help entry for tuning parameters.
05/09/2019 16:04:01   You can press 3 Alt_L's (Left "Alt" key) in a row to 
05/09/2019 16:04:01   repaint the screen, also see the -fixscreen option for
05/09/2019 16:04:01   periodic repaints.
05/09/2019 16:04:01 
05/09/2019 16:04:01 XFIXES available on display, resetting cursor mode
05/09/2019 16:04:01   to: '-cursor most'.
05/09/2019 16:04:01   to disable this behavior use: '-cursor arrow'
05/09/2019 16:04:01   or '-noxfixes'.
05/09/2019 16:04:01 using XFIXES for cursor drawing.
05/09/2019 16:04:01 
05/09/2019 16:04:01 WARNING: XTEST extension not available (either missing from
05/09/2019 16:04:01   display or client library libXtst missing at build time).
05/09/2019 16:04:01   MOST user input (pointer and keyboard) will be DISCARDED.
05/09/2019 16:04:01   If display does have XTEST, be sure to build x11vnc with
05/09/2019 16:04:01   a working libXtst build environment (e.g. libxtst-dev,
05/09/2019 16:04:01   or other packages).
05/09/2019 16:04:01 No XTEST extension, switching to -xwarppointer mode for
05/09/2019 16:04:01   pointer motion input.
05/09/2019 16:04:01 *********************************************************
05/09/2019 16:04:01 * No XTEST or DEC-XTRAP protection from XGrabServer !!! *
05/09/2019 16:04:01 * DEADLOCK if your window manager calls XGrabServer !!! *
05/09/2019 16:04:01 *********************************************************
05/09/2019 16:04:01 
05/09/2019 16:04:01 The RECORD X extension was not found on the display.
05/09/2019 16:04:01 If your system has disabled it by default, you can
05/09/2019 16:04:01 enable it to get a nice x11vnc performance speedup
05/09/2019 16:04:01 for scrolling by putting this into the "Module" section
05/09/2019 16:04:01 of /etc/X11/xorg.conf or /etc/X11/XF86Config:
05/09/2019 16:04:01 
05/09/2019 16:04:01   Section "Module"
05/09/2019 16:04:01   ...
05/09/2019 16:04:01       Load    "record"
05/09/2019 16:04:01   ...
05/09/2019 16:04:01   EndSection
05/09/2019 16:04:01 
05/09/2019 16:04:01 
05/09/2019 16:04:01 XKEYBOARD: number of keysyms per keycode 7 is greater
05/09/2019 16:04:01   than 4 and 51 keysyms are mapped above 4.
05/09/2019 16:04:01   Automatically switching to -xkb mode.
05/09/2019 16:04:01   If this makes the key mapping worse you can
05/09/2019 16:04:01   disable it with the "-noxkb" option.
05/09/2019 16:04:01   Also, remember "-remap DEAD" for accenting characters.
05/09/2019 16:04:01 
05/09/2019 16:04:01 X FBPM extension not supported.
05/09/2019 16:04:01 X display is capable of DPMS.
05/09/2019 16:04:01 --------------------------------------------------------
05/09/2019 16:04:01 
05/09/2019 16:04:01 Default visual ID: 0x20
05/09/2019 16:04:01 Read initial data from X display into framebuffer.
05/09/2019 16:04:01 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/7680
05/09/2019 16:04:01 *** unrecognized option(s) ***
05/09/2019 16:04:01 	[1]  -multiptr
05/09/2019 16:04:01 For a list of options run: x11vnc -opts
05/09/2019 16:04:01 or for the full help: x11vnc -help
05/09/2019 16:04:01 
05/09/2019 16:04:01 Here is a list of removed or obsolete options:
05/09/2019 16:04:01 
05/09/2019 16:04:01 removed: -hints, -nohints
05/09/2019 16:04:01 removed: -cursorposall
05/09/2019 16:04:01 removed: -nofilexfer, now the default.
05/09/2019 16:04:01 
05/09/2019 16:04:01 renamed: -old_copytile, use -onetile
05/09/2019 16:04:01 renamed: -mouse,   use -cursor
05/09/2019 16:04:01 renamed: -mouseX,  use -cursor X
05/09/2019 16:04:01 renamed: -X,       use -cursor X
05/09/2019 16:04:01 renamed: -nomouse, use -nocursor
05/09/2019 16:04:01 renamed: -old_pointer, use -pointer_mode 1
X Error of failed request:  BadShmSeg (invalid shared segment parameter)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  2 (X_ShmDetach)
  Segment id in failed request:  0x0
  Serial number of failed request:  33
  Current serial number in output stream:  37

Running on Ubuntu 18.04, I can run x11vnc but not with the option -multiptr. I have also tried x11vnc 0.9.16 and have the same problem.

**Comment by bk138** [comment]
Your x11vnc is not built with XInput2. Please attach the build logs.

**Comment by bk138** [comment]
Also, how do you start x11vnc?

**Comment by bk138** [comment]
Tentatively closing, please re-open in case you have more info.
