### ISSUE TITLE
Keyboard doesnt work at all with UserLAnd

### ISSUE THREAD

**Issue by valadina223** [bk138/multivnc#33]
**Describe the bug**
I set up a UserLAnd install on an Android 9 (LineageOS) phone. UserLAnd works fine in combination with MultiVNC. I can connect, move the mouse, use the onscreen mouse buttons. However, if I toggle keyboard the keyboard pops up but I cannot press any key on the keyboard. It's there but it doesnt work. Instead if I press a button those touches go right 'through' the keyboard and are recognized by the underlying 'virtual mouse'. 

**To Reproduce**
1) Install MultiVNC
2) Install UserLAnd
3) Connect to a VNC session
4) Press the menu button and then toggle keyboard
5) Keyboard pops up but doesnt respond to any input.

**Expected Behavior**
The keyboard should respond to the input via touch.

**For the Desktop Version (please complete the following information):**
OS: Ubuntu@UserLAnd
XORG: The one that comes with UserLAnd

**For the Mobile Version (please complete the following information):**
Android 9 (LineageOS 16)

**Additional information**
Why does that seem to be a MultiVNC bug? Tried realVNC with the same setup, the keyboard there works as it should.

**Comment by bk138** [comment]
Thanks for reporting! Does it work with another VNC _server_?

**Comment by valadina223** [comment]
Good question. I couldn't tell. What would be a fast VNC server setup to test?

**Comment by bk138** [comment]
you could try to install x11vnc on Linux

**Comment by valadina223** [comment]
Doesn't work either. Must be a problem with MultiVNC

**Comment by bk138** [comment]
Thing is, I can't reproduce, it just works for me :-/ 
How to proceed from here - is your setup/hardware anything special?

**Comment by valadina223** [comment]
Hm, good question. Do you also run Android 9? LineageOS 16 by any chance? I use the standard keyboard that comes with the OS. 

Step by step would be:
1) Get UserLAnd from F-Droid
2) Launch it and choose XFCE of LXDE - this sets up a Linux distribution on your phone (careful, you need bandwith and space on the phone)
3) When done (it's really just three clicks) launch that desktop environment. It automatically starts MultiVNC if installed.
4) Try to use the keyboard. It pops up but it's not working.

No idea how I could help otherwise. I guess a video wouldn't make sense. If you need a logcat output I could give you that too. But would you be willing to try UserLAnd first? There's another project like that called AnLinux. Same problem with MultiVNC. Like I said. Tried realVNC from playstore and it works with the keyboard.

**Comment by serayrosh** [comment]
I am experiencing the same issue when using the AOSP Keyboard, which LineageOS uses by default.

So you might be able to reproduce the issue by switching to the AOSP Keyboard.

**Comment by bk138** [comment]
is there any keyboard on fdroid or play store where it fails?

**Comment by valadina223** [comment]
Seems you can get it here on APK mirror: [AOSP Keyboard](https://www.apkmirror.com/apk/lineageos/android-keyboard-aosp-2/android-keyboard-aosp-2-9-release/android-keyboard-aosp-9-2-android-apk-download/)

**Comment by bk138** [comment]
> Seems you can get it here on APK mirror: [AOSP Keyboard](https://www.apkmirror.com/apk/lineageos/android-keyboard-aosp-2/android-keyboard-aosp-2-9-release/android-keyboard-aosp-9-2-android-apk-download/)

Mhh, this crashes on Android 8.

**Comment by xini-source** [comment]
I am affected too.
If you need the keyboard for Android 8, find it here: [AOSP 8 Keyboard](https://www.apkmirror.com/apk/lineageos/android-keyboard-aosp-2/android-keyboard-aosp-2-8-1-0-release/android-keyboard-aosp-8-1-0-android-apk-download/)

**Comment by bk138** [comment]
> I am affected too.
> If you need the keyboard for Android 8, find it here: [AOSP 8 Keyboard](https://www.apkmirror.com/apk/lineageos/android-keyboard-aosp-2/android-keyboard-aosp-2-8-1-0-release/android-keyboard-aosp-8-1-0-android-apk-download/)

That crashes as well on opening. Is there any keyboard on f-droid or Play Store where the issue happens? Or: a simulator config would be super helpful, too!

**Comment by bk138** [comment]
Just tried with UserLAnd on Android 8, Samsung S7, SwiftKey keyboard, connecting to a pure Debian session, (WM looks like twm or the like?) -> works.

**Comment by xini-source** [comment]
Please, try with [Simple Keyboard](https://f-droid.org/en/packages/rkr.simplekeyboard.inputmethod/) from F-Droid. Doesn't work like AOSP Keyboard.

**Comment by bk138** [comment]
Finally, this exposes the issue. Does happen with other VNC Server as well, not limited to UserLAnd.

**Comment by bk138** [comment]
Works in portrait mode, not in landscape... https://stackoverflow.com/questions/4336762/disabling-the-fullscreen-editing-view-for-soft-keyboard-input-in-landscape?answertab=active#tab-top might help?

**Comment by xini-source** [comment]
Well, I'd prefer a real fix instead of using portrait mode. Would be great if you could look into that.

**Comment by bk138** [comment]
Tried several approaches, to no avail so far.

**Comment by bk138** [comment]
https://stackoverflow.com/questions/27860497/android-lollipop-soft-keyboard-doesnt-accept-keypresses-with-gl-surface

**Comment by bk138** [comment]
https://weekly-geekly.github.io/articles/320788/index.html

**Comment by xini-source** [comment]
Great, thanks for the fix.

**Comment by xini-source** [comment]
@bk138, did you try that fix? I compiled the latest version of MultiVNC but the keyboard is still fullscreen and still doesnt work. Is there a setting I am missing?

**Comment by bk138** [comment]
Yeah, before 1fb5a8309c3515468fbceffd01d5653b009214db Simple Keyboard would expose this very issue, after 1fb5a8309c3515468fbceffd01d5653b009214db not anymore.

**Comment by xini-source** [comment]
Hm, I see.

This is what I get after git log:

```~/multivnc$ git log
commit 0eb1f80805f0de59b8ab7f4aefb8e48314dff3c3 (HEAD -> master, origin/master, origin/HEAD)
Author: Christian Beier <dontmind@freeshell.org>
Date:   Fri Oct 25 09:55:01 2019 +0200

    Android: tell softkeyboard to not go fullscreen
    
    Some software keyboards like to go fullscreen in landscape mode with the user visible effect
    of popping up with a quick fullscreen flash, then being visible on the lower half of the screen
    but not accepting input.
    
    re https://stackoverflow.com/a/33742840/361413
    
    Closes #33
```

Still, after building the apk MultiVNC still shows the same behavior, keyboard doesnt work. Any step I missed?

**Comment by bk138** [comment]
Does not seem so. Either your build is somehow flawed or the fix is, for your environment. You might try to:

* see if the debug log appears
* add some more flags as in the SO link

**Comment by xini-source** [comment]
Hm, good question.

Here is a log output:

```--------- beginning of system
10-25 17:20:55.309  5133  5133 I android.hardware.wifi@1.0-service: enter getLinkLayerStats
10-25 17:20:55.310  5133  5133 I android.hardware.wifi@1.0-service: enter getLinkLayerStatsInternal
10-25 17:20:55.379  5133  5133 I android.hardware.wifi@1.0-service: Successfully getLinkLayerStats.
--------- beginning of main
10-25 17:20:57.480  5151  5183 E BufferQueueProducer: [AtchDlg:com.coboltforge.dontmind.multivnc/com.coboltforge.dontmind.multivnc.VncCanvasActivity#0] disconnect: not connected (req=1)
10-25 17:20:57.480  7944  8032 W libEGL  : EGLNativeWindowType 0x71aa476010 disconnect failed
10-25 17:20:57.480  7944  8032 D OpenGLRenderer: endAllActiveAnimators on 0x71b57efe00 (ExpandedMenuView) with handle 0x71b32cdbc0
10-25 17:20:57.503  5617  5617 E InputMethodService: Unexpected null in startExtractingText : mExtractedText = null, input connection = InputConnectionWrapper{idHash=#916b515 mMissingMethods=}
10-25 17:20:57.508  5617  5617 I LatinIME: Starting input. Cursor position = -1,-1
10-25 17:20:57.510  5617  5617 I InputAttributes: InputType.TYPE_NULL is specified
10-25 17:20:57.517  5617  5617 E InputMethodService: Unexpected null in startExtractingText : mExtractedText = null, input connection = InputConnectionWrapper{idHash=#916b515 mMissingMethods=}
10-25 17:20:57.534  5617  7222 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
10-25 17:20:57.745  5151  5427 W SurfaceFlinger: Attempting to set client state on removed layer: AtchDlg:com.coboltforge.dontmind.multivnc/com.coboltforge.dontmind.multivnc.VncCanvasActivity#0
10-25 17:20:57.745  5151  5427 W SurfaceFlinger: Attempting to destroy on removed layer: AtchDlg:com.coboltforge.dontmind.multivnc/com.coboltforge.dontmind.multivnc.VncCanvasActivity#0
10-25 17:20:58.417  5133  5133 I android.hardware.wifi@1.0-service: enter getLinkLayerStats
10-25 17:20:58.417  5133  5133 I android.hardware.wifi@1.0-service: enter getLinkLayerStatsInternal
10-25 17:20:58.456  5133  5133 I android.hardware.wifi@1.0-service: Successfully getLinkLayerStats.
10-25 17:20:58.547  5431  5522 D SensorService: [SO] 0.120 0.093 9.929
10-25 17:21:01.496  5133  5133 I android.hardware.wifi@1.0-service: enter getLinkLayerStats
10-25 17:21:01.496  5133  5133 I android.hardware.wifi@1.0-service: enter getLinkLayerStatsInternal
10-25 17:21:01.533  5133  5133 I android.hardware.wifi@1.0-service: Successfully getLinkLayerStats.
10-25 17:21:04.573  5133  5133 I android.hardware.wifi@1.0-service: enter getLinkLayerStats
10-25 17:21:04.573  5133  5133 I android.hardware.wifi@1.0-service: enter getLinkLayerStatsInternal
10-25 17:21:04.651  5133  5133 I android.hardware.wifi@1.0-service: Successfully getLinkLayerStats.
```

Do you see anything suspicious?

**Comment by bk138** [comment]
You should see the `onCreateInputConnection` log from 1fb5a8309c3515468fbceffd01d5653b009214db when the keyboard opens.

**Comment by xini-source** [comment]
Hm, can you explain that a bit more? The log I posted is the whole log from when the keyboard opens. I am not sure about the meaning of your sentence.

**Comment by bk138** [comment]
> Hm, can you explain that a bit more? The log I posted is the whole log from when the keyboard opens. I am not sure about the meaning of your sentence.

Sorry for being unclear. The mentioned commit has [this line](https://github.com/bk138/multivnc/commit/1fb5a8309c3515468fbceffd01d5653b009214db#diff-312574cf1efee44bb56a517802339f36R893) that triggers a log output of `onCreateInputConnection`. This should appear for the following fix to apply. If it does not, the fix can't work

**Comment by bk138** [comment]
Another idea: could you try with a5d2b2c121eeeced550e543dd3a6d5ede0ee25d6 ?

**Comment by xini2** [comment]
Lost my login credentials... 

Tried https://github.com/bk138/multivnc/commit/a5d2b2c121eeeced550e543dd3a6d5ede0ee25d6
Doesn't work either unfortunately. If it helps: The green menu button also doesn't work once the keyboard is visible.

**Comment by bk138** [comment]
Yeah, the whole view is disabled in that case. FWIW, I'll do a new release for so @valadina223 @serayrosh can try out the fix and report if it works for them.

**Comment by bk138** [comment]
@valadina223 @serayrosh did 1.8.4 fix the issue for you?

**Comment by serayrosh** [comment]
1.8.4 did not solve it for me. Still having the same issue when using AOSP Keyboard.

**Comment by bk138** [comment]
@serayrosh does androidvnc expose the same behavior?

**Comment by k3tan172** [comment]
I'm also having these issues with the keyboard.

**Comment by bk138** [comment]
@k3tan172  does androidvnc expose the same behavior? Which version are you using?

**Comment by k3tan172** [comment]
Yes, androidvnc exposes the same behaviour. I'm using 1.8.8.
I tried on my Pixel 3a and it works perfectly.
My OnePlusOne with LineageOS doesn't work. I can get it to work eventually, but I'm not able to reproduce how the keyboard starts to magically work. But for certain, upon initial connection, the keyboard doesn't work and exhibits the behaviours described in the original post.
It's probably something to do with LineageOS 16.

**Comment by k3tan172** [comment]
The solution is once you've connected, click back until it prompts you 'Are you sure you want to disconnect?' Click 'Cancel'. Toggle Keyboard and it should now work.

**Comment by bk138** [comment]
@k3tan172 Does it make a difference whether you toggle via menu or long-press-and-then-icon?
