### ISSUE TITLE
Too many bookmarks due to automatic bookmarking, launched from UserLAnd

### ISSUE THREAD

**Issue by valadina223** [bk138/multivnc#34]
**Describe the bug**
Using MultiVNC in combination with UserLAnd. Every time I log into a desktop session a new bookmark is created within MultiVNC. Those add up eventually. 

Could you make automatic bookmarking optional? Otherwise those get too much eventually. Had to delete 25 or so bookmarks one by one.

Thanks.

**To Reproduce**
1) Install MultiVNC
2) Install UserLAnd
3) Set up desktop inside UserLAnd
4) Connect to desktop via UserLAnd app
5) Bookmark is created in MultiVNC

**Expected Behavior**
No bookmark is created within MultiVNC

**Comment by bk138** [comment]
Thanks for reporting! Is this about the Android client? 

TBH, there is no automatic bookmarking i know of - which version are you using?

**Comment by valadina223** [comment]
Yes, it's about the Android client. MultiVNC version is 1.8.2.
Are you sure about the automatic bookmarking? Because every time I use MultiVNC with UserLAnd a bookmark is created. Looks like this then, every bookmark is the same.

![2019-10-21-163808](https://user-images.githubusercontent.com/56826715/67215204-5e051400-f421-11e9-9213-94ccda92767a.png)

**Comment by bk138** [comment]
funky. is this launched from some other app or manually via home screen?

**Comment by valadina223** [comment]
It is launched by UserLAnd.

**Comment by bk138** [comment]
What happens when launched from Home Screen? BTW, do you have a link regarding UserLAnd, I got no idea what this actually is :-)

**Comment by valadina223** [comment]
When I launch it nothing happens. It just launches. No auto bookmarking.

Hehe, I thought UserLAnd is the new thing everybody plays with now. It's basically an environment to run a full Debian, Ubuntu, Arch etc. on your Android phone. It starts a local VNC server and you connect with MultiVNC.

Sure, find it here: `https://github.com/CypherpunkArmory/UserLAnd`
Best to install it from here: `https://f-droid.org/packages/tech.ula/`

**Comment by bk138** [comment]
So this might be related to the way UserLAnd launches MultiVNC - do you maybe have a hint on how/where they do this?

**Comment by bk138** [comment]
This i can repro and confirm.
