### ISSUE TITLE
modern icon

### ISSUE THREAD

**Issue by nathaneltitane** [bk138/multivnc#36]
implementation of a more moden multi vnc icon.

![multivnc](https://user-images.githubusercontent.com/5674757/67871905-866acd80-fb07-11e9-95d1-46a8b360bc00.png)

**Comment by bk138** [comment]
this looks nice, I'd like something that resembles the original icon's kraken look more as it implies the multicast character.

**Comment by nathaneltitane** [comment]
Ah, I see. well this was just a proposal that was done in litterally 5 minutes - didn'T put much thought into it.

Will try something when i have time

**Comment by bk138** [comment]
Tentatively closing for now, please re-open when/if you have had time to try something new.
