### ISSUE TITLE
Feature Request: send right clicks when using a hardware mouse

### ISSUE THREAD

**Issue by sudomain** [bk138/multivnc#37]
**Is your feature request about the Desktop Multivnc or the Mobile MultiVNC?**

* [ ] Desktop (wxWidgets)
* [ X ] Mobile (Android)

**Is your feature request related to a problem? Please describe.**
I sometimes use a USB mouse connected to my phone using an [USB OTG](https://en.m.wikipedia.org/wiki/USB_On-The-Go) cable when I need more clicking precision than the touchscreen offers. Currently the right click button sends the same signal as the Android Back button, and MultiVNC asks me "Are you sure you want to disconnect?". It would be great if MultiVNC could interpret a mouse right right click and then send then right click signal like it does when tapping MultiVNC's on screen/virtual mouse button.

**Describe the solution you'd like**
If a hardware right click is used in the MultiVNC (and the VNC server OS supports it), then a context menu should open. Ideally it would act just like the on-screen right mouse button that MultiVNC already has.

**Describe alternatives you've considered**

**Additional context**
These SO questions might be a good reference:
https://stackoverflow.com/questions/12705117/handle-all-mouse-events-in-android
https://stackoverflow.com/questions/10041295/android-usb-mouse-right-click-correct-behaviour-ics/29311126#29311126

**Comment by bk138** [comment]
@sudomain let me know if 1.8.5 really fixed it for you, can't test 100% here.

**Comment by sudomain** [comment]
Got the update from FDroid. Works like a charm
