### ISSUE TITLE
No menu on Samsung tab A 

### ISSUE THREAD

**Issue by teledyn** [bk138/multivnc#39]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android): Android 7.1.1

**Describe the bug**

Samsung galaxy tab a, connects to raspberry pi3, but the hamburger menu does not open. It makes an audible click, but I expect a menu to open with keybd mode, exit, etc. 

 - Android version: 7.1.1
 - Installed from Play Store or F-Droid: f-droid

**Comment by bk138** [comment]
Looking into this!

**Comment by teledyn** [comment]
Let me know if there is anything I need to test!

**Comment by bk138** [comment]
https://developer.samsung.com/forum/thread/a/201/271391?db=5&state=accountcheckdogeneratedstatetext

**Comment by bk138** [comment]
@teledyn Could you pls try with [this apk](https://send.firefox.com/download/09bb20e7f1f0d3c0/#Zhph3adRNagHryJtHABHcw)

**Comment by teledyn** [comment]
Works! Or at least the menu button works and I can change mouse mode,
keyboard etc - will follow up if anything critical is missing once I get
into using it.

Thanks!

**Comment by bk138** [comment]
Great, this will be in 1.8.8.

**Comment by bk138** [comment]
@teledyn please check the upcoming 1.8.9 version once it's there, we switched the menu implementation and got rid of the workaround.
