### ISSUE TITLE
Android: Code cleanup

### ISSUE THREAD

**Issue by gujjwal00** [bk138/multivnc#44]
There are some issues (related to style & formatting)  that I can fix. I would like your feedback/suggestions before I start.

**Issues**
- Code formatting: Currently there are different styles of formatting (eg. tab vs space) used. We can follow a consistent style.
- Missing license: Some files are missing license headers. We should fix it.

**Why fix it**
- Increased readability
- Reduced maintenance efforts
- Easy on-boarding for new contributors

**Comment by bk138** [comment]
What changes do you propose?

**Comment by gujjwal00** [comment]
Proposal: 

**Code style**
We can use default style of Android Studio with following tweaks:

- Maximum consecutive blank lines: 1
- Blank lines before closing brace '}': 0

*Note*: Default Android Studio style uses spaces for indentation instead of tabs. Let me know if you prefer tabs.

**License**
- For files which don't have **any** license/copyright header, add GPLv3 header with your name.
- For files which **only** have your name, add GPLv3 header too.
- We can also add GPLv3 header to XML files if thats okay with you.

Remaining files are attributed to Michael A. MacDonald. I believe these are under GPLv2 license but I could not find a definitive answer. If these files are licensed under GPLv2, we can add GPLv2 or GPLv3 (whichever you prefer) header.

**Refactoring**
I am refactoring `VNCConn` to remove dependency on `VncCanvas`. It will allow us to keep `VNCConn` alive across activity restarts so that we can enable rotation of `VncCanvasActivity`.

Thanks.

**Comment by bk138** [comment]
* Code Style: ACK
* License: if the file were written by me, ACK
* Rotation: Please have a look at #15 for that

**Comment by bk138** [comment]
Considering this closed by bffe1a8398b83147900b33d94cb0d3466c0050b0.
