### ISSUE TITLE
Android: Mixed line terminators

### ISSUE THREAD

**Issue by gujjwal00** [bk138/multivnc#55]
Currently following files uses `CRLF` line terminators:

- COLORMODEL.java
- ColorModel256.java
- ColorModel64.java
- ColorModel8.java
- Utils.java

All other files use `LF`. We should use same for these files to be consistent.
Also, git (with default config) converts `CRLF` to `LF` when committing. Then small changes appears as if the whole file is changed.

I can submit a PR but GitHub also says that every line is changed.

**Comment by bk138** [comment]
Most of these files will go away, no need to touch them :-)

**Comment by gujjwal00** [comment]
OK
