### ISSUE TITLE
Readme or wiki file: android activities list

### ISSUE THREAD

**Issue by nathaneltitane** [bk138/multivnc#57]
With the growing trend of Termux based Linux environments and scripts emerging from this, it would be great to have an on-hand list of supported activities for your application.

This comes in handy to help initialize, populate or start VNC sessions directly from Termux or any other capable application/activity.

Thank you for your consideration!

**Comment by bk138** [comment]
I don't really understand what exactly you propose ;-) Is this about https://github.com/bk138/multivnc/blob/master/android/app/src/main/AndroidManifest.xml and the activities in there?

**Comment by nathaneltitane** [comment]
I've written a BASH setup script to help novice users get acquainted with Termux, VNC and setting up their own portable linux environment.

I'd like to be able to create the new vnc connection/bookmark in your application through the script and automatically launch it when called on via termux using your application's activities/intent statements

**Comment by gujjwal00** [comment]
For creating new connections,  [vnc](https://en.m.wikipedia.org/wiki/List_of_URI_schemes) URI scheme is already supported (See the manifest @bk138 mentioned above). You can directly launch new connection using activity manager:
`am start-activity -d vnc://host:port`

Once connected, user can add that connection to bookmarks.

**Comment by nathaneltitane** [comment]
@gujjwal00 thank you so much - slight correction, and for future references:

am start -d vnc://host:port

@bk138  :

Also, is there any way to create the bookmark automatically for future connections/reference?
I'm not really sure which activity to call or what intent/flag to call under bookmarks for that to happen.

**Comment by gujjwal00** [comment]
@nathaneltitane Please note that both commands are equivalent: [AM source](https://github.com/aosp-mirror/platform_frameworks_base/blob/e80b45506501815061b079dcb10bf87443bd385d/services/core/java/com/android/server/am/ActivityManagerShellCommand.java#L159)

**Comment by sudomain** [comment]
Glad I found this as I'm doing a similar project to @nathaneltitane. I'll just add that both of you correct: The commands are equivalent except for the version of am that is packaged with Termux. `am start-activity ...` in Termux will return `Error: unknown command 'start-activity'` so `am start` is the one Termux supports.

**Comment by sudomain** [comment]
@gujjwal00 does MultiVNC implement the full VNC URI scheme? I've tried:

`am start -d  vnc://localhost:5901?VncPassword=redacted`

As well as:
`am start -d  vnc://localhost:5901?VncPassword=redacted&SecurityType=2`

But each time MultiVNC will prompt me for the password

**Comment by nathaneltitane** [comment]
@sudomain you can enforce localhost and make do without using the password for session access like I do

**Comment by sudomain** [comment]
> you can enforce localhost and make do without using the password for session access

I agree and I do this already. Binding to localhost and specifying a password in a URI are not mutually exclusive security strategies though. A person may have two VNC clients (e.g. multivnc and a closed source app) that they assign different levels of trust to. They may only want for the closed source app to access less trusted VNC servers running on localhost (no password), while also giving MultiVNC access to more trusted VNC servers on localhost (with a password to prevent the closed source app from accessing the more trusted server)

**Comment by gujjwal00** [comment]
Well, specifying password is supported but not the way RFC recommends it. You can do something like this:

`am start -d vnc://localhost:5901/C24bit/mypassword/`. 

The structure is: `vnc://host/colormodel/password/`. You **have** to specify color-model so that the password is at second place. 


Support for RFC 7869 can be added relatively easily for the most part because `Uri` class already parses the URI string for us and we just have to put those values in `ConnectionBean`. But I think this should be discussed in a separate issue.
