### ISSUE TITLE
Feature request: smoother zoom for pinch gesture

### ISSUE THREAD

**Issue by sudomain** [bk138/multivnc#59]
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your feature request about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android): Mobile
 - If Mobile, installed from Play Store or F-Droid: F-Droid

**Is your feature request related to a problem? Please describe.**

The currect zoom is a bit "jerky". It sometimes doesn't register and stops zooming in/out in the middle of a pinch, resulting in the user doing many pinches to get the desired zoom. I tested this with different devices to make sure it was a specific device quirk.

**Describe the solution you'd like**

A smoother zoom that is more like the zoom experienced in the popular web browsing apps (firefox, chrome, etc).  It currently feels like the zoom stops when the fingers stop moving. It might be better to stop the zoom when one or both fingers are lifted

**Describe alternatives you've considered**

**Additional context**

**Comment by gujjwal00** [comment]
I had worked on this issue but decided to wait for integration of native LibVNCClient before PRs.

@bk138 If you are ok with this, I can submit them.

**Comment by bk138** [comment]
Yeah sure. Review will be slow as I am busy with job and family,but it will happen🙂

**Comment by gujjwal00** [comment]
>Review will be slow

No problem!  BTW, Thanks for all the work done on these projects :+1:.

---

Plan for this issue:
- [ ] **1. Remove unused code:** We are now using OpenGL for scaling but there is some old code which is still there. It is not used anymore and should be removed.
- [ ] **2. Replace custom scale gesture detector:** We are using a custom detector for scaling gestures. It was used to detect gestures in API levels  <8. Now we require API level 19. Hence we can use the detector provided by Android.
- [ ] **3. Enable smooth scaling:** Remove the 'jerky' behavior. As @sudomain indicated, scaling is aborted if the change in focal point of scaling is large. This code appears to be a side-effect of custom scaling detector (hence step 2 is required).

*Optional:* After step 3, scaling logic should be simple enough to be moved entirely inside `VncCanvas`. We can then remove `ZoomScaling` & `AbstractScaling`. This is not required for this issue but can be done as general refactoring.

**Comment by bk138** [comment]
Is this now closed by a537b9bf2af00c700f53200922d3c2ba4bc6913c ?

**Comment by gujjwal00** [comment]
> Is this now closed by a537b9b ?

Yes.

There is slight refactoring I am hoping to do but doesn't block this issue.

**Comment by bk138** [comment]
Well then...
