### ISSUE TITLE
Phone vs tablet behaviour 

### ISSUE THREAD

**Issue by mcastillof** [bk138/multivnc#64]
Hello, I'm a long time user of MultiVNC and  I like it a lot. I'm trying to use it now in a tablet with a big eInk screen. There seems to be different behaviors between this device and a phone, and I'm not sure that you are aware of it, since I couldn't find anything about it in the help of the app or here in the repo. Both devices are running MultiVNC 1.8.9, the tablet running Android 9, the phone running LineageOS 16 (Android 9).

From the phone I'm moving the mouse by swapping in the screen. Taps don't work. Mouse clicks are done with the bottom screen buttons. If Toggle Mouse Buttons is disabled, then taps works, where one tap is a left click, and two taps is a right click. In the Tablet, mouse movement by swipe is not working, because swipe seems to be interpreted as a multiple tap, and tap is interpreted as a left click, which I think is fine, since with a big screen is easy to tap where you want to click. I couldn't find a way to do a right click without toggling the mouse buttons.

In my phone I am able to scroll by two finger swap. In the tablet I can't do that. There's also a problem with the zoom. In my phone I long press to show the zoom +, keyboard and zoom - icons at top, but in the tablet long press is like a tap, like a mouse click, so is not showing those buttons.

**Comment by bk138** [comment]
Thanks for the info! Which way to go from here do you propose? I tested the app on a 10" Asus tablet, it works as expected. One idea: try your tablet with another app and see if the issue is there, too.

**Comment by mcastillof** [comment]
I did a test with Document Viewer (a PDF viewer) nad androidVNC, both from F-droid. Both apps behaves in the exact same way in my phone and my tablet.

I see that if there is no way te reproduce the problem, it will be hard to track/debug it. This eInk reader, Max3 (from Onyx Boox), is a bit convoluted (has two touch layers, a capacitive one for finger touch, and a Wacom one, for stylus). I wouldn't be surprised if the device is the problem. There are a few system upgrades that I didn't want to install, maybe it is time now. Hopefully it will just fix the problem.

Maybe we should close this issue as I see no way to reproduce the problem.
