### ISSUE TITLE
remove top right options overlay

### ISSUE THREAD

**Issue by jacquinot-eric** [bk138/multivnc#66]
there should be an option to remove the top right menu overlay
![20200518_200648](https://user-images.githubusercontent.com/61070211/82245672-b367bc00-9943-11ea-9db2-13ae604092d0.jpg)

**Comment by bk138** [comment]
Thanks for the suggestion. How would you like to access the menu functionality in case the button got removed?

**Comment by jacquinot-eric** [comment]
you already have something in place so you could add it there also...
(202252.jpg)

on top of that maybe there is a way to prevent the top android
notifications bar and the android navigation bar to popup when the mouse
goes to the edge of the screen (202459.jpg)

i attached 2 screenshots

your app is almost commercial grade and as good as realvnc viewer but it is
imho missing those two small things...

maybe you should make a pay version with more customizations as i believe
many people won't mind pay a few bucks for it...

**Comment by bk138** [comment]
Let's keep track in #35, which I found out was reported earlier :-)
