### ISSUE TITLE
Android: Remove toast notification for scaling

### ISSUE THREAD

**Issue by gujjwal00** [bk138/multivnc#70]
Can we remove Toast notifications which appear during scaling?

They are very distracting because if I zoom-in that's because I want to look more closely at some part of the screen. But, out of nowhere, I will get a Toast of current zoom level. It steals focus and breaks workflow.

Moreover, they provide useless information. Zoom level is a meaningless number to user because user will zoom in/out untill it's comfortable to watch.

**Comment by bk138** [comment]
I personally like the info about the current zoom level. It also does not steal keyboard focus and disappears quite quickly. Let's leave this open to collect community feedback over time.

**Comment by gujjwal00** [comment]
Can we at least replace toasts with a `TextView` indicating current level? 

Something like this ( in top-left corner):
![image](https://user-images.githubusercontent.com/27951674/84596009-cacd9280-ae78-11ea-92ba-5eb3550af36b.png)
It would only be visible during scaling.

**Comment by bk138** [comment]
> Can we at least replace toasts with a `TextView` indicating current level?
> 
> Something like this ( in top-left corner):
> ![image](https://user-images.githubusercontent.com/27951674/84596009-cacd9280-ae78-11ea-92ba-5eb3550af36b.png)
> It would only be visible during scaling.

That looks like a good idea!

**Comment by bk138** [comment]
Closed by 076819ad842c7d76dec032b85da92c1364c655f9, thanks!
