### ISSUE TITLE
Feature request: shift the canvas up/down when the keyboard is toggled

### ISSUE THREAD

**Issue by sudomain** [bk138/multivnc#76]
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Is your feature request about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android): android
 - If Mobile, installed from Play Store or F-Droid: fdroid

**Is your feature request related to a problem? Please describe.**

When enabled, many keyboards cover part of the VNC canvas (not sure if this is the correct technical term).
**Describe the solution you'd like**

When the keyboard is enabled via the `Toggle Keyboard` button, the view of the display should be shifted upward on the screen to prevent the keyboard from covering part of it. When it is disabled via `Toggle keyboard` or the system Back button, the display should be shifted downward by the same amount.
**Describe alternatives you've considered**

**Additional context**

**Comment by bk138** [comment]
Thanks for the idea! Why would cutting off the top of the screen be better then cutting off the bottom?

**Comment by sudomain** [comment]
I should've included a screenshot (sorry); a picture's worth a thousand words:

![Screenshot_2020-07-05-16-32-32](https://user-images.githubusercontent.com/30786326/86541735-4604f000-bedd-11ea-8b02-aabd11675591.png)

Note the keyboard is covering ~1/2 of my desktop and the bottom toolbar (The default Xfce bottom toolbar). There is a decent amount of black space/padding along the top of the canvas, that the desktop environment isn't using. I think when the keyboard gets enabled, the desktop should be shifted into that unused space. Even if the whole height can't fit, it would make better use of screen real estate.

**Comment by bk138** [comment]
Ah OK, didn't realise we're talking about portrait mode  - makes sense there.

**Comment by deliciouslytyped** [comment]
This is the main reason I switched to VNC Viewer. I think the canvas area should be resized to fit the visible area.
Is there any chance this could be fixed in the nearish future?

**Comment by bk138** [comment]
> This is the main reason I switched to VNC Viewer. I think the canvas area should be resized to fit the visible area.
> Is there any chance this could be fixed in the nearish future?

I'm putting this on the near-future agenda. Nonetheless, help and contributions welcome! It also helps to put out an incentive at https://issuehunt.io/r/bk138/multivnc/issues/76 ;-)

**Comment by bk138** [comment]
https://stackoverflow.com/questions/1964789/move-layouts-up-when-soft-keyboard-is-shown

**Comment by mr-south-guo** [comment]
If dynamically adjusting layout is too difficult at the moment, how about this: if the view-port's height is less than the screen's height, draw the view-port at the top instead? This will leave the bottom part enough space to show the soft-keyboard.

**Comment by gujjwal00** [comment]
> if the view-port's height is less than the screen's height

Well that is the whole issue. If we ask Android to make our View fullscreen, it stays fullscreen even if keyboard is visible.

**Comment by bk138** [comment]
Closed by #85
