### ISSUE TITLE
Input not where the circle is (intended for mouse)

### ISSUE THREAD

**Issue by velasta** [bk138/multivnc#8]
Super fun app to use and play with. I been looking at the code and wanna use this to connect my broken screen android phone (broken screen) to my working screen phone. I put the VNC server on the broken one and was able to connect nicely.

**One problem is to do inputs I can only input where the PURPLE CIRCLE is. Is there a way to modify the code (of this Client) so I can do standard android inputs at any point on the screen and not drag the purple circle to click there?**

Thank you :)
-CHEERS

**Comment by bk138** [comment]
This is the way input focus works. You can maybe change focus with tab.

**Comment by velasta** [comment]
Hello Christian can you please elaborate on what you mean by "tab" to change the focus (is this something in the settings or in the source code?). 

Looking at your source code, it seems that **VncCanvasActivity.java**  deals with mouse movement and touch inputs but I'm trying to get ** the inputs to be at any point of the screen ** and I'm not sure where to find this :/

**Comment by velasta** [comment]
Please correct me if I'm wrong Christian since your more experienced and knowledgeable on this them I am. I've looked through every java file and can't seem to pin-point what to modify to not have inputs go through ONLY in the purple circle area but be accepted everywhere (other clients work good like VNC Viewer but their not open source)

Kindest

**Comment by velasta** [comment]
Dear Christian, I'm sorry to bother you I was just hoping you might have an insight into this or if you might know who to contact to figure this out. It would be greatly appreciated. Thank you so much in advance for any pointer.

**Comment by bk138** [comment]
In short, the answer is no. Please read https://en.wikipedia.org/wiki/Focus_(computing) together with https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst. The conclusion is: single input focus with VNC.
