### ISSUE TITLE
Feature request: screen orientation hook to send commands to server

### ISSUE THREAD

**Issue by sudomain** [bk138/multivnc#84]
**Is your feature request about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android): Android
 - If Mobile, installed from Play Store or F-Droid: Fdroid

**Is your feature request related to a problem? Please describe.**

When MultiVNC changes orientation to portrait or landscape, I'd like for my server (tigervnc) to automatically change display resolution.

**Describe the solution you'd like**

I'd like MultiVNC to be able to execute a script containing `xrandr` commands on the vncserver. tigervnc allows resizing of the desktop by default, and I can do it on-the-fly in the terminal, but I'd like for MultiVNC to issue the commands when it changes orientation.
**Describe alternatives you've considered**

**Additional context**

This is probably a separate issue, but when I resize the display with `xrandr --fb`, MultiVNC still shows the old display size until I disconnect and reconnect. Is there a way to avoid reconnecting?

**Comment by gujjwal00** [comment]
> I'd like MultiVNC to be able to execute a script containing xrandr commands on the vncserver

I don't think think MultiVNC (or any VNC client) can execute arbitrary commands on remote server.

Although RFB protocol allows frame size negotiation, MultiVNC doesn't support that yet.

>This is probably a separate issue, but when I resize the display with xrandr --fb, MultiVNC still shows the old display size until I disconnect and reconnect. 

Same as above.

>Is there a way to avoid reconnecting?

Not yet.

**Comment by bk138** [comment]
> I'd like MultiVNC to be able to execute a script containing `xrandr` commands on the vncserver. tigervnc allows resizing of the desktop by default, and I can do it on-the-fly in the terminal, but I'd like for MultiVNC to issue the commands when it changes orientation.

This is not directly possible with VNC/RFB. What you can do is define a key combo on the target host to execute whatever command you like and send that key combo from MultiVNC whenever you like. (On-rotation key combos are too special and won't be added.)

> This is probably a separate issue, but when I resize the display with `xrandr --fb`, MultiVNC still shows the old display size until I disconnect and reconnect. Is there a way to avoid reconnecting?

This _is_ a separate issue. Please open a new one for this :-)
