### ISSUE TITLE
Question: how to disable the disconnect dialogue on right click

### ISSUE THREAD

**Issue by alexanderadam** [bk138/multivnc#87]
Thank you so much for MultiVNC.
How can I disable the disconnect dialogue on right click?
I have a keyboard cover and naturally I'm using the right click of the touchpad without wanting to disconnect.

**Comment by bk138** [comment]
Are you using the Andoid or the desktop variant?

Which MultiVNC version is it?

Are you using an extenal keyboard with touchpad? 

How would I be able to reproduce your issue?

**Comment by alexanderadam** [comment]
Oh, I thought there might be already an option to disable this.

But here you are:

MultiVNC: [`1.9.3` from F-Droid](https://f-droid.org/de/packages/com.coboltforge.dontmind.multivnc/#1.9.3)
OS and version: Android 10, [Samsung Galaxy Tab S6](https://en.wikipedia.org/wiki/Samsung_Galaxy_Tab_S6)

I'm using a keyboard cover with touchpad ([as mentioned earlier](https://github.com/bk138/multivnc/issues/87#:~:text=I%20have%20a%20keyboard%20cover%20and%20naturally%20I'm%20using%20the%20right%20click%20of%20the%20touchpad)).

> How would I be able to reproduce your issue?

I guess emulating a 'right click' in an emulator. But I have no insights how MultiVNC is developed or debugged, so I don't know

**Comment by bk138** [comment]
It should basically just get you a right click per default, as per da6d81f837e697f8c2e14f28be4832213c3d1a0b. Maybe your device sends a different source ID, I'll have a look.

**Comment by alexanderadam** [comment]
Maybe a touchpad is [`SOURCE_MOUSE_RELATIVE`](https://developer.android.com/reference/android/view/InputDevice#SOURCE_MOUSE) instead of [`SOURCE_MOUSE`](https://developer.android.com/reference/android/view/InputDevice#SOURCE_MOUSE)?

**Comment by bk138** [comment]
Please have a try with this one: 
[app-debug.zip](https://github.com/bk138/multivnc/files/5238292/app-debug.zip)

**Comment by alexanderadam** [comment]
The bug is still present in this release

**Comment by bk138** [comment]
Here's another debug apk that should a popup on right click with a number. Please write down that number here.

[app-debug.zip](https://github.com/bk138/multivnc/files/5238826/app-debug.zip)

**Comment by alexanderadam** [comment]
Keycode: `12290`

**Comment by bk138** [comment]
> Keycode: `12290`

That's ... special. Found [this](https://fossies.org/linux/SDL2/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L1943)

**Comment by bk138** [comment]
Here goes another .apk:

[app-debug.zip](https://github.com/bk138/multivnc/files/5239079/app-debug.zip)

**Comment by alexanderadam** [comment]
This is working perfectly :+1: (it still shows the keycode notification, though)

**Comment by bk138** [comment]
That was expected, nicee.

**Comment by alexanderadam** [comment]
thank you so much for fixing this and your work on multivnc in general!

**Comment by bk138** [comment]
You're welcome! I'm always happy about a 5-star rating on GPlay, some blog post, telling your tech friends about it. Whatever works! :-)
