### ISSUE TITLE
Samasung keyboard First letter only issue

### ISSUE THREAD

**Issue by xradiation** [bk138/multivnc#91]
**Is your bug report about the Desktop Multivnc or the Mobile MultiVNC?**
 - Desktop (wxWidgets) or Mobile (Android): Android

**Describe the bug**
The issue is that when I type only the fist letter shows up what ever is after that is essentially completely ignored, strangely enough if I keep pressing the Enter key after every single letter it works just fine.

**To Reproduce**
Use a samsung device with android Q ( haven't used any other device / version )
VNC to a VM ( Qemu/KVM )
Try to type

**Expected Behavior**
You Know ... writing

**For the Mobile Version (please complete the following information):**
 - Android version: 10 ( Q )
 - Installed from Play Store or F-Droid: F-Droid

**Comment by bk138** [comment]
* Is that with a hardware or software keyboard?

* Does it happen when connecting to other hosts as well?

**Comment by xradiation** [comment]
hi @bk138,
- It's the samsung default software keyboard 
- Yeah I've tried both textual & graphical (Linux/BSD) operating systems, the issue persists regardless

**Comment by bk138** [comment]
Alright! Some more things:

* Which version of the app are you using?

* Are you using native connection mode or the "old" one?

**Comment by xradiation** [comment]
- MultiVNC 1.9.4
- The default one "old"
- Here is a screen shot of what it looks like when typing on the samsung keyboard :

![Screenshot_20200929-140958](https://user-images.githubusercontent.com/61669101/94564228-ab0f7e00-025f-11eb-8b81-74d938d49114.jpg)
Typing "exit" but it only reads "e".

- And I've been able to test it using "AnySoftKeyboard", and it seems that it works just fine : 

![Screenshot_20200929-141703](https://user-images.githubusercontent.com/61669101/94564602-10636f00-0260-11eb-8dfe-a4dc6e308bb5.jpg)

It most likely an issue with the samsung keyboard, since it acts weirdly with termux as well.

**Comment by bk138** [comment]
Ha, funnily I was experiencing this on a Samsung tablet now as well - seems their soft keyboard has some issues.
