### ISSUE TITLE
Can't build Android project

### ISSUE THREAD

**Issue by veitk** [bk138/multivnc#92]
Working on MacOS Catalina 10.15.7
Sorry i'm no expert in make files and stuff like that, maybe you could help me get this up and running.

the prepareLibreSSL.h replies with:

readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
./prepareLibreSSL.sh: line 5: cd: /libressl: No such file or directory
sed: 1: "update.sh": invalid command code u
./prepareLibreSSL.sh: line 8: ./autogen.sh: No such file or directory

Afterwards Android Studio complains with:

file failed to open for reading (No such file or directory):

    /Users/......./bk138/multivnc/libressl/ssl/VERSION

Any hints?

**Comment by bk138** [comment]
No idea, TBH I never tried on Mac so might just not work with the current script. Quick google attack yields https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by veitk** [comment]
Thanks for the link, that one helped. There are some more Cmake errors on the mac, so i switched to my windows machine and it gives me "NDK not configured" ... i guess i will get a coffee now and try to fix that.

**Comment by bk138** [comment]
How did you solve the readelf issue? We should add this to the script then.

**Comment by veitk** [comment]
i tried it by changing readlink to "greadlink" in the file. but there are more cmake errors then, which i didn't have on windows. now i can't fix the "NDK not configured" bug in android studio :(  (btw which version of NDK are you using?)

if i have time to invest the mac cmake bugs i will let you know

**Comment by veitk** [comment]
okay i cloned the repository on the mac again. 
after submodule init / update i editedthe prepareLibreSSL to use "greadlink" (by the way on your android page is the part "git submodule init" missing)

so now i have the exact same problem as on windows: NDK not configured. But it is. Everything is set up.

**Comment by bk138** [comment]
Works for me on MacOS 10.15.6, Android Studio 4.0.1. I can't help you with the NDK setup but am able to share config on request. Those are the installed SDK tools, for instance

![Bildschirmfoto 2020-10-01 um 19 18 10](https://user-images.githubusercontent.com/80450/94841821-da1e1f00-041a-11eb-9d26-29855453adea.png)

**Comment by veitk** [comment]
hey thanks for your reply. 
my mistake was that i imported the wrong folder :(

now i figured out that i have to take some steps to get libressl to build.

**Comment by bk138** [comment]
> now i figured out that i have to take some steps to get libressl to build.

There should be no manual step involved, it's all in https://github.com/bk138/multivnc/blob/master/android/app/src/main/cpp/CMakeLists.txt#L21

**Comment by veitk** [comment]
i removed the targets "ssl" and "crypto" since my problems is the installation of libressl. thx for your help!
