### ISSUE TITLE
Server address not trimmed

### ISSUE THREAD

**Issue by GalegoPreto** [bk138/multivnc#99]
When trying to connect to a VNC server on 

Mobile (Android)
Version 1.9.7

on entering the VNC server IP address using auto complete inserts a whitespace after the address, which results in a connection error because it's not trimmed from the string (and not visible)

**To Reproduce**
Enter beginning of address (i.e. 192.168.) and autocomplete the rest (or just enter a space after a valid address)
Click on connect
Error "VNC Connection failed!"

**Expected behaviour**
Whitespaces are removed to be more tolerant to stupid users

**Screenshots**
![Screenshot_20201101-101836](https://user-images.githubusercontent.com/73775314/97799050-a443a480-1c2b-11eb-8bf0-79d0f4b93dd7.jpg)
![Screenshot_20201101-101842](https://user-images.githubusercontent.com/73775314/97799052-aad21c00-1c2b-11eb-90a5-0d676bddebba.jpg)

**For the Mobile Version (please complete the following information):**
 - Android version: 10
 - Installed from Play Store

**Comment by bk138** [comment]
That's been there for a long time. Thanks for spotting @GalegoPreto !
